### ISSUE TITLE
BIMSufer connects successfully but the UI loads  nothing.

### ISSUE THREAD

**Issue by reomomoon** [opensourceBIM/BIMsurfer-before2019#102]
Greetings.I am sorry that English is not my mother language，so maybe the follows i express is not very clear，so if you have any problems,I will try to explain it again.
The first problem is BIMSurfer connect successfully but the UI load nothing but a black progressing bar. I saw a same question in issues, but I think my problem is different from his/hers after watching the description of the program. I will post my console as follow. Hope you can help me.
## My system is Windows 7, chrome and firefox are all tried.

"async" "request" [object Object] bimserverapi.js:421
"response" [object Object] bimserverapi.js:430
"async" "request" [object Object] bimserverapi.js:421
"response" [object Object] bimserverapi.js:430
"async" "request" [object Object] bimserverapi.js:421
"async" "request" [object Object] bimserverapi.js:421
"response" [object Object] bimserverapi.js:430
"response" [object Object] bimserverapi.js:430
"async" "request" [object Object] bimserverapi.js:421
"response" [object Object] bimserverapi.js:430
"loadScene: " [object Error] "BIMSURFER.Viewer<.loadGeometry@file:///E:/BIMSurfer/BIMsurfer-Bryan/api/BIMSURFER/Viewer.js:393
loadProject/</</<.buttons.Load/<@file:///E:/BIMSurfer/BIMsurfer-Bryan/js/example1.js:243
BIMSURFER.Viewer<.loadScene@file:///E:/BIMSurfer/BIMsurfer-Bryan/api/BIMSURFER/Viewer.js:341
loadProject/</</<.buttons.Load@file:///E:/BIMSurfer/BIMsurfer-Bryan/js/example1.js:233
._createButtons/</props.click@file:///E:/BIMSurfer/BIMsurfer-Bryan/lib/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.js:9230
x.event.dispatch@file:///E:/BIMSurfer/BIMsurfer-Bryan/lib/jquery-1.10.2/jquery-1.10.2.min.js:5
x.event.add/v.handle@file:///E:/BIMSurfer/BIMsurfer-Bryan/lib/jquery-1.10.2/jquery-1.10.2.min.js:5
" [object Object] [object Arguments] Viewer.js:344
"loadScene ERROR" [object Error] "BIMSURFER.Viewer<.loadGeometry@file:///E:/BIMSurfer/BIMsurfer-Bryan/api/BIMSURFER/Viewer.js:393
loadProject/</</<.buttons.Load/<@file:///E:/BIMSurfer/BIMsurfer-Bryan/js/example1.js:243
BIMSURFER.Viewer<.loadScene@file:///E:/BIMSurfer/BIMsurfer-Bryan/api/BIMSURFER/Viewer.js:341
loadProject/</</<.buttons.Load@file:///E:/BIMSurfer/BIMsurfer-Bryan/js/example1.js:233
._createButtons/</props.click@file:///E:/BIMSurfer/BIMsurfer-Bryan/lib/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.js:9230
x.event.dispatch@file:///E:/BIMSurfer/BIMsurfer-Bryan/lib/jquery-1.10.2/jquery-1.10.2.min.js:5
x.event.add/v.handle@file:///E:/BIMSurfer/BIMsurfer-Bryan/lib/jquery-1.10.2/jquery-1.10.2.min.js:5
## " [object Object] [object Arguments]

Besides, what bothers me a lot is the version problem. Wiki and issues forum suggest the latest BIMServer connects the latest BIMSurfer, but as what I have tried, the latest BIMSurfer（master）cannot connect to the latest BIMServer（1.3.0-FINAL-2014-04-25..On the other hand , the version connected successfully  is bimsurfer-bryan and bimserver-1.3.0-RC5-2014-2-11,so why is this happened? And what version you suggest me to use?
And in the end, whether the BIMSurfer could be used in Android？B/S structure is what I chosen now so I mean if I want to develop a 3D display software and more importantly giving it more functionality in Android based on webGL , Is BIMSurfer a useful and efficient tool? Can you give me some advice?
Sorry again for my poor English. Hope you can see what bothers me and heip me figure it out.Thanks again. I will always watching the dynamic of the Website.
                                                                                                             Mona from China

**Comment by navneetccna** [comment]
Facing the same problem with new bim surfer the old one is working fine and bim server by default is also using the old one http://test.bimsurfer.org/

**Comment by reomomoon** [comment]
Thanks for your reply.So your bim surfer can display ifc file correctly? My
bim surfer can connect successfully but cannot load anything just like the
picture in attachment.Did you ever met the problem？My console has post in
the issues block  if you need it.Hope you can help me.Thanks again.

2014-05-02 13:27 GMT+08:00 Navneet Garg notifications@github.com:

**Comment by reomomoon** [comment]
Today afer I reset the  latested bim server it  works very well,so the first problem has been resolved.Keep moving.
