### ISSUE TITLE
Cannot pan by middle mouse

### ISSUE THREAD

**Issue by ccnick16** [opensourceBIM/BIMsurfer-before2019#106]
Hi,
I cannot pan by press middle mouse. In latest code in file PickFlyOrbit.js, there is no handler for pan: 

```
actionMove: function(x, y) {
        if(this.orbitDragging) {
            this.yaw += (x - this.lastX) * this.direction * 0.1;
            this.pitch -= (y - this.lastY) * 0.1;
            this.orbiting = true;
        } else if(this.panDragging) {

        }

        this.lastX = x;
        this.lastY = y;
}
```

There is a previous version can do it, however the bimserver 1.3 cannot do it anymore.

**Comment by vpanchal** [comment]
Update the PickFlyOrbit.js to latest. Fix for panning by Michal Zeman, CAD Studio
