### ISSUE TITLE
BIMsurfer GUI

### ISSUE THREAD

**Issue by ZemanM** [opensourceBIM/BIMsurfer-before2019#108]
Hello,

I install/use latest version of the BIMsurfer and BIMserver. I can load and view my model sucessfully but UI functionality from the left panel is not working: object info, tree, loaded project.

Can you suggest what is needed to configure or what I am doing wrong? My server is behind the firewall and is not accesible from internet - can it be the reason?

Thanks in advance for any help!
Michal

![image](https://cloud.githubusercontent.com/assets/8223309/3642814/3bc611a6-10c8-11e4-8025-5e7d1d6576d7.png)

**Comment by rubendel** [comment]
That hasn't been implemented in the BIMsurfer example. Have a look at BIMvie.ws, is has a working tree and object properties.

**Comment by ZemanM** [comment]
Thank you Ruben!
