### ISSUE TITLE
Global ID of Selected element/node

### ISSUE THREAD

**Issue by venkysoft** [opensourceBIM/BIMsurfer-before2019#110]
HI, 
I have been trying to fetch the Global ID of the selected element.
In the ClickSelect.js I was being able to pull nodeId. can someone help me fetch Global Id

**Comment by coryasilva** [comment]
You could try a rest call to the bimserver at Bimsie1LowLevelInterface.getDataObjectByOid

In a past version of bimserver I just sent all the GUIDs, TAGs, and OIDs for each object and applied them as data attributes to the node.  This was favorable when integrating with other databases.

**Comment by venkysoft** [comment]
Thanks for the info. 
In that API call, it is asking for roid. Can you please help out what is that roid and how that can be determined for a project/file. 
Or else if  you can tell me which version of BIMSurfer has the code to get the GUID of the selected object that would be much helpful for us to integrate with our modules. 

Thansk & Regards,Venkatesh. V

Date: Wed, 30 Jul 2014 01:37:47 -0700

**Comment by coryasilva** [comment]
ROID is the Revision Id of the project.  That can be found by using Bimsie1ServiceInterface.getAllProjects
Bimsie1ServiceInterface.getProjectByPoid
etc.  

Load up bimserver and go to http://localhost:port/admin  There you should find a link to console that has all these commands.  It is documentation by example -- very useful and fun.

**Comment by venkysoft** [comment]
Sorry to bother you so much.
But, if I could crack this BIMSurfer then it would help me a lot in my work.

I have made a call to getAllProjects and here is the response object which among this is the roid which can be used to make the Bimsie1LowLevelInterface.getDataObjects so that I can get all the data objects of the project.
Thanks & Regards,Venkatesh. V

Date: Wed, 30 Jul 2014 02:22:17 -0700

**Comment by venkysoft** [comment]
Sorry to bother you so much.But, if I could crack this BIMSurfer then it would help me a lot in my work.I have made a call to getAllProjects and here is the response object which among this is the roid which can be used to make the Bimsie1LowLevelInterface.getDataObjects so that I can get all the data objects of the project.
{  "response": {
    "result": [
      {
        "__type": "SProject",
        "checkouts": [],
        "concreteRevisions": [
          65540
        ],
        "createdById": 131074,
        "createdDate": 1406019578846,
        "description": "",
        "exportLengthMeasurePrefix": "meter",
        "extendedData": [],
        "geoTagId": 65541,
        "hasAuthorizedUsers": [
          131074
        ],
        "id": 2,
        "lastConcreteRevisionId": 65540,
        "lastRevisionId": 65539,
        "logs": [
          65552
        ],
        "modelCheckers": [],
        "name": "SampleIFC",
        "oid": 131073,
        "parentId": -1,
        "revisions": [
          65539
        ],
        "rid": 2,
        "services": [],
        "state": "ACTIVE",
        "subProjects": []
      },
      {
        "__type": "SProject",
        "checkouts": [],
        "concreteRevisions": [],
        "createdById": 131074,
        "createdDate": 1406019589816,
        "description": "",
        "exportLengthMeasurePrefix": "meter",
        "extendedData": [],
        "geoTagId": 196613,
        "hasAuthorizedUsers": [
          131074
        ],
        "id": 4,
        "lastConcreteRevisionId": -1,
        "lastRevisionId": -1,
        "logs": [
          196624,
          131097
        ],
        "modelCheckers": [],
        "name": "SampleIFCFile",
        "oid": 327681,
        "parentId": -1,
        "revisions": [],
        "rid": 2,
        "services": [],
        "state": "DELETED",
        "subProjects": []
      },
      {
        "__type": "SProject",
        "checkouts": [],
        "concreteRevisions": [],
        "createdById": 131074,
        "createdDate": 1406019628690,
        "description": "",
        "exportLengthMeasurePrefix": "meter",
        "extendedData": [],
        "geoTagId": 327685,
        "hasAuthorizedUsers": [
          131074
        ],
        "id": 6,
        "lastConcreteRevisionId": -1,
        "lastRevisionId": -1,
        "logs": [
          327696,
          65561
        ],
        "modelCheckers": [],
        "name": "sample",
        "oid": 589825,
        "parentId": -1,
        "revisions": [],
        "rid": 2,
        "services": [],
        "state": "DELETED",
        "subProjects": []
      },
      {
        "__type": "SProject",
        "checkouts": [],
        "concreteRevisions": [],
        "createdById": 131074,
        "createdDate": 1406019608407,
        "description": "",
        "exportLengthMeasurePrefix": "meter",
        "extendedData": [],
        "geoTagId": 262149,
        "hasAuthorizedUsers": [
          131074
        ],
        "id": 5,
        "lastConcreteRevisionId": -1,
        "lastRevisionId": -1,
        "logs": [
          262160,
          196633
        ],
        "modelCheckers": [],
        "name": "sampleifcproject",
        "oid": 458753,
        "parentId": -1,
        "revisions": [],
        "rid": 2,
        "services": [],
        "state": "DELETED",
        "subProjects": []
      }
    ]
  }
}

Date: Wed, 30 Jul 2014 02:22:17 -0700

**Comment by dlabz** [comment]
"lastRevisionId"

**Comment by coryasilva** [comment]
Sorry I do not understand; what is your question?

**Comment by venkysoft** [comment]
Hey,

Is there anyway we can directly zoom the viewer to particular object based on the nodeId. 

Thanks & Regards,
Venkatesh. V

---
