### ISSUE TITLE
Multi-select on objects

### ISSUE THREAD

**Issue by shazada** [opensourceBIM/BIMsurfer-before2019#112]
We would like to have Multi-select on the object to retrieve their GUID.

At the moment it's not possible to Multi-select. This is also a nice feature when people take screenshots of their models and want to emphasize elements.

**Comment by reomomoon** [comment]
I'm also stuck in the problem.

**Comment by heseir** [comment]
Did anyone manage to find a solution for the multi-selection of objects issue?

**Comment by rubendel** [comment]
This is working now in V2
