### ISSUE TITLE
Local setup of bimsurfer is not working getting below error.

### ISSUE THREAD

**Issue by vpanchal** [opensourceBIM/BIMsurfer-before2019#113]
Hi,
I have downloaded the Bimsurfer latest version and extracted in local dir. Now when I try to connect with bimserver which is running on another machine it gives me error.

![screenshot from 2014-12-03 18 29 11](https://cloud.githubusercontent.com/assets/846490/5280705/b1e4f4bc-7b1a-11e4-8cb4-2769fd830e46.png)

**Comment by rdarricau** [comment]
I've just got the same. Not in local, but between two domains. GLOBAL is not defined.

**Comment by rubendel** [comment]
Thanks for reporting, fixed in https://github.com/opensourceBIM/BIMserver/commit/fc1f79d899107714ea06360a0174536aed5e161c

**Comment by rdarricau** [comment]
<3
