### ISSUE TITLE
Newer version of BIMSurfer not loading Left side tree.

### ISSUE THREAD

**Issue by vpanchal** [opensourceBIM/BIMsurfer-before2019#114]
Using exmaple1.html of bimsufter it is not loading left side tree even after model get's loaded. 
Can anyone sugget where I can do changes so that tree can start loading ?

**Comment by dyrqp** [comment]
I met the same problem.

**Comment by rubendel** [comment]
The tree is not a part of BIMsurfer anymore, have a look at BIMvie.ws for a working tree.
