### ISSUE TITLE
BimSurfer not loading the Model from BimServer in Example1 provided

### ISSUE THREAD

**Issue by nirojans** [opensourceBIM/BIMsurfer-before2019#116]
Hi all,

Installed BimServer 1.3.0 (As the same issue mentioned below occured in the 1.4.0 version switched to 1.3.0 version ) [1]

And when I try to run the Bim Surfer example1 the login is successful with the Bim Server and it displays all the projects and when selecting a project to view error occurs in the GeometryLoader.js file. So the page remains frozen without loading anything. 

This happens when example1.js executes the line number 253. (o.viewer.loadGeometry(geometryLoader);)

![screen shot 2015-06-15 at 1 00 57 pm](https://cloud.githubusercontent.com/assets/5965496/8155144/dc580a86-135e-11e5-8bae-802ebf885432.png)

So tried several IFC files to check whether the issues comes because of corrupted model,but the issue remains the same. And models are perfectly viewable in the Bimviews.

[1] - https://github.com/opensourceBIM/BIMsurfer/issues/94

Hope to hear from you.

Kind regards,

Nirojan.

**Comment by juranki** [comment]
It looks like the `GeometryLoader.setLoadTypes()` is expecting a list of objects with `name` attribute. However, an object where keys are the typenames is provided.

With the following hack in `example1.js`, the geometry is successfully loaded:

![image](https://cloud.githubusercontent.com/assets/6607/9898792/04c62898-5c5e-11e5-9b1c-be691b25b2ba.png)

(I won't try to make a pull req, because I don't know the codebase well enough, yet)

**Comment by starcn16888** [comment]
me too！

**Comment by sshniro** [comment]
Hi,

The current Bim Surfer code is not compatible with the new BIM Surfer version. The current version works with BIM Surfer 1.4.0 March Release Candidate. But still had some issues and aothms-patch-1[1] works fine with the BIM Surfer March Release Candidate.

[1] - https://github.com/opensourceBIM/BIMsurfer/tree/aothms-patch-1 

Best Regards,
S.Nirojan

**Comment by sshniro** [comment]
Hi juranki,

Yea did the same work around previously by going through the older commits and it worked. Thanks for sharing. :)

**Comment by rubendel** [comment]
Fixed: https://github.com/opensourceBIM/BIMsurfer/commit/215d7b172d8f1099d6d0aa77cc9d042e1e9ecc9f
