### ISSUE TITLE
BIMsurfer does not connect to BIMserver

### ISSUE THREAD

**Issue by px3l** [opensourceBIM/BIMsurfer-before2019#119]
I have installed BIMserver on a remote server and it works great. When I point my browser to BIMsurfer, it loads the example1.html and asks me to connect to the BIMserver. After inputting the correct address and details and pressing connect it just greys out the connect button and does nothing. 

I get the error: 'Uncaught TypeError: errorCallback is not a function'
![bimsurfer](https://cloud.githubusercontent.com/assets/11406845/10023937/8fbacb5a-614c-11e5-8458-a4b866f847fb.PNG)

**Comment by rubendel** [comment]
Versions please

**Comment by px3l** [comment]
Apologies, it is BIMserver 1.4.0 on Tomcat 8.0.26 on Ubuntu14.04x64. Latest BIMsurfer cloned from repo.

**Comment by rubendel** [comment]
Ok the error is "Could not connect", the example1.js does not handle the error, so that's what the JavaScript error is about. Are you sure you have included the port and optional context path?

**Comment by px3l** [comment]
yes, i have IP:8080 which is tomcats default webapps port and then the context path /BIMserver

IP:8080/BIMserver

If I go to that URL it loads the BIMserver great, which I have set up and it loads BIMviews and whatever IFC files I upload load fine too. 

EDIT-- I have just updated to the newest BIMserver release (23rd Sep) but still have the same problem

**Comment by rubendel** [comment]
Just to make sure, does it include http:// as well?

**Comment by px3l** [comment]
yes it does, http://IP:8080/BIMserver

**Comment by rubendel** [comment]
Is bimsurfer served from a webserver as well? I am running out of ideas. In the network tab of your chrome console, do you see bimserverapi.js being loaded?

**Comment by px3l** [comment]
Yes so BIMsurfer is from the same webserver, just in its own directory. I can see it is loading bimserverapibootstrap.js but the only entry for bimserverapi.js is this: bimserverapi.js?_=1443008307187

![error](https://cloud.githubusercontent.com/assets/11406845/10044358/3127d6ae-61f2-11e5-83ee-2d4945211e74.PNG)

**Comment by bb14521** [comment]
I have installed BIMserver through .jar file. when I point my browser to BIMsurfer, it loads the example1.html and asks me to connect  with the BIMserver.  Then i am fill the required the  address and details and pressing connect it just greys out the connect button and does nothing.

![screenshot from 2015-10-01 15 28 40](https://cloud.githubusercontent.com/assets/5606588/10218089/e258b8d4-6851-11e5-8f20-c020dd9815d8.png)
![screenshot from 2015-10-01 15 31 51](https://cloud.githubusercontent.com/assets/5606588/10218091/e40546d4-6851-11e5-903a-2e9df473e20d.png)

**Comment by rubendel** [comment]
Are there any projects with revisions for the specified user? If no, that's why the list is empty.

**Comment by bb14521** [comment]
On Thu, Oct 1, 2015 at 6:36 PM, Ruben de Laat notifications@github.com wrote:

> Are there any projects with revisions for the specified user? If no, that's why the list is empty.

yes, i add one project but unable to upload any ifc file in server,

## 

---

Bharat Bhushan Rathore
http://bhushanbharat.wordpress.com/
http://techbbr.blogspot.in/
https://github.com/bb14521

**Comment by rubendel** [comment]
So the problem is not really in BIMsurfer is it?

**Comment by niharikapothani** [comment]
Hello, 
I'm a beginner. Learning how to use BIM and BIMsurfer. 
I'm using the example1.html file and I'm not able to connect BIMSurfer to the my BIMserver running on tomcat 7 in ubuntu 16.04. The connect button grey's out and does nothing. 
Could you please help?

**Comment by niharikapothani** [comment]
my BIMserver is https://locathost:8080

**Comment by bb14521** [comment]
Is it working on local ?  How do you install BIMserver! using Jar file or something else ?

**Comment by niharikapothani** [comment]
Yeah. I deployed the war file of BIM server. And then tried connecting the BIM surfer to BIM server.

**Comment by bb14521** [comment]
Which version of BIMsever are you running?  And have you read  Documentation for BIMsurfer ?

[(https://github.com/opensourcebim/BIMsurfer)]

**Comment by bb14521** [comment]
There is any .ifc file for in specific user ?

**Comment by niharikapothani** [comment]
i'm running the BIMserver1.4 version.
I have a IFC file uploaded in the BIMServer

**Comment by bb14521** [comment]
Go through this video 
https://www.youtube.com/watch?v=jEVLRP8UxCw
from 0:00 to 0:19 sec. 
hope this will help.  one thing more javascript must be enable (basically its auto enable). 
And have you read Documentation of BIMsurfer ?

**Comment by bb14521** [comment]
On Fri, Jul 1, 2016 at 8:26 PM, niharikapothani
notifications@github.com wrote:

> i'm running the BIMserver1.4 version.
> I have a IFC file uploaded in the BIMServer

Put Login(Which is used to login in BIMserver) in the column of Email
and try with your local ip instead localhost. (https:127.0.0.1:8080/)

## 

---

Bharat Bhushan Rathore
https://in.linkedin.com/in/rathor0023

http://bhushanbharat.wordpress.com/
https://github.com/bb14521
"We don't receive wisdom; we must discover it for ourselves after a
journey that no one can take for us or spare us."
