### ISSUE TITLE
Possibly limit the camera's orbit at the top (and maybe at the floor?)

### ISSUE THREAD

**Issue by rehno-lindeque** [opensourceBIM/BIMsurfer-before2019#12]
Possibly limit the camera's orbit at (0,0,1) and (0,0,-1) (or possibly at the floor?) to avoid turning it upside down - this is a bit of a trade-off. Locking the camera doesn't feel very smooth to the user, but turning the camera upside down is also a little unnatural - especially when viewing buildings since these can't usually be viewed from these strange angles.

**Comment by rehno-lindeque** [comment]
It might not be a great idea to limit the camera to the floor though - first of all it might not be all that easy to determine at what height the floor and secondly, some buildings may have basements etc. Rather opt on the side of user freedom here.

**Comment by berlotti** [comment]
No problem... the whole idea of BIM is to evaluate a building model on places where you can't in real life :-)

**Comment by rehno-lindeque** [comment]
Ok, sounds good! :)
