### ISSUE TITLE
Problem when reading long bigger than 2^31-1

### ISSUE THREAD

**Issue by pandreev** [opensourceBIM/BIMsurfer-before2019#121]
We had a problem displaying a model when some of the oids were bigger than 2^31-1.

It was caused by throwing away the last 4 bytes when reading long in the DataInputStream.js

**Comment by rubendel** [comment]
Thanks for the issue! There was already an issue here: https://github.com/opensourceBIM/BIMserver/issues/242, but I was wrong on how soon this problem was going to manifest, it is indeed at 2^32-1. I'll give a higher priority to this issue.

**Comment by rubendel** [comment]
This has been fixed, thanks to a pull request
