### ISSUE TITLE
Can't connect to the latest BIMserver

### ISSUE THREAD

**Issue by antarktikali** [opensourceBIM/BIMsurfer-before2019#126]
I have the BIMserver 1.4.0(build 2015-11-04) running and I can't connect to it from BIMsurfer.

It seems like the current BIMsurfer is looking for some "bimserverapi.js", which doesn't exist in the BIMserver. Under the js folder in BIMserver, there are 7 files beginning with bimserverapi(such as "bimserverapi_BimServerApi.js") but even when I modified the "bimserverapibootstrap.js" file of the BIMsurfer to include request that script, it doesn't work.

**Comment by bgavrilman** [comment]
same here. Any developments?

**Comment by sechanbask** [comment]
I can't connect too.

What is the difference between Bimsever we can connect to and the last one ?

**Comment by rantidev1** [comment]
I am also having the same problem . My BimServer's version is : 1.4.0

**Comment by rubendel** [comment]
BIMsurfer master branch should work with BIMserver master branch. BIMsurfer master branch definitely won't work with BIMserver 1.4.0.

**Comment by rantidev1** [comment]
Apart from master branch of BIMServer and BIM Surfer , could you please tell me which other versions of  BIMServer and BIMSurfer are compatible ?

**Comment by digitalportico** [comment]
i am also having the same issue. which Bimsurfer compatble with  BIMserver 1.4.0. ?
