### ISSUE TITLE
BimSurfer 0.0.4 is not able to show 3d Model while using BIM Server 1.4.0

### ISSUE THREAD

**Issue by rantidev1** [opensourceBIM/BIMsurfer-before2019#128]
Please check attached image for detail and please find below details of BIM Server:

JS: GeometryLoader.js

Current version    1.4.0
Current version dat      23-09-2015
Schema version      20

![bimsurfer_issue](https://cloud.githubusercontent.com/assets/9971904/12951348/30c10102-d012-11e5-9cf2-01394922917f.png)

**Comment by rubendel** [comment]
0.0.4 is a test is just a release to test the build system, these "releases" are made from the master branch of the repository and they do not work with BIMserver 1.4.0. They work with BIMserver master branch (which is unstable and unreleased).
