### ISSUE TITLE
Viewer zoom in/out scrolls page as well.

### ISSUE THREAD

**Issue by aothms** [opensourceBIM/BIMsurfer-before2019#134]
Event should be properly captured and not bubble up.

This is noticeable e.g in https://github.com/opensourceBIM/BIMsurfer/blob/V2/example_APIreference.html

**Comment by xeolabs** [comment]
Same deal with arrow keys for rotation - will deal with it in xeoEngine (https://github.com/xeolabs/xeoengine/issues/92)

**Comment by aothms** [comment]
Ok perfect, sorry for the dup then :)

**Comment by xeolabs** [comment]
Oh no problem! Let's track it here as well though, so that we can QA in context of BIMSurfer.
