### ISSUE TITLE
rotation around mousepoint

### ISSUE THREAD

**Issue by berlotti** [opensourceBIM/BIMsurfer-before2019#136]
rotation is now around a single (center) point. It should be around the point (on the object) where the mouse is.

**Comment by xeolabs** [comment]
Is this the desired UX: when user clicks once on an object, view is not fitted to object, but camera now orbits that point?

**Comment by aothms** [comment]
I don't think the camera should move upon a single click as is too different from similar applications. Move the camera upon double click is fine for me. Single click would then only set the selection state.

Some viewers always orbit around the unprojected point in 3d space where the mouse button was pressed down. Some viewers also render this point (see image), I wouldn't render it.

![solibri](https://cloud.githubusercontent.com/assets/1096535/14862039/01954d72-0cb0-11e6-82c8-2da59ac72f93.png)

I don't think orbiting around this point is perfect UX, but I think it is desirable to have something else then an arbitrary point the user cannot really influence. If nobody has a better idea I would settle on this convention. If the user mouses down on a point in the scene without geometry, you would still need some arbitrary distance (e.g size of the model) to unproject the point and orbit.

I don't think it's easy/possible to read the depth buffer in opengl es / webgl. For me it would be fine as well to ray-intersect only with the object bounding boxes to unproject the point to orbit around.

**Comment by xeolabs** [comment]
Ok this is not a problem - xeoEngine is able to ray-pick to find the 3D intersection point on the object when we click on it, so there's no need to do a ray-intersect with the bounding box.

Currently, when we click on an object, the view is fitted to the object, while the object is translated so that the camera "target" position is set to the 3D intersection point on the object.

**Comment by berlotti** [comment]
Agree with Thomas

**Comment by xeolabs** [comment]
Just want to confirm if this the correct UX:
1. double-click on object
2. camera does not move, but the clicked 3D point has now become the rotation center point
3. mouse down
4. drag mouse
5. camera orbits about center point, orbiting about the point's vertical (Z) axis with mouse X-movement, and about the horizontal (X) axis with mouse Y-movement
6. mouse up
7. move mouse somewhere else
8. mouse down
9. drag mouse
10. camera orbits about center point, same as at (5)

And while orbiting, the clicked point remains effectively fixed at the same location on the canvas.

**Comment by xeolabs** [comment]
Managed to get the exact required behaviour working - now just tidying up.
