### ISSUE TITLE
remove spotlight

### ISSUE THREAD

**Issue by berlotti** [opensourceBIM/BIMsurfer-before2019#137]
remove the spotlight behind the camera. Light should be behind the camera, but no spot

**Comment by xeolabs** [comment]
There are two directional lights behind the camera - do you just want one directional light, pointing in the same direction as the camera?

**Comment by aothms** [comment]
I think what is meant here is not so much an issue with the lights, but the specularity of the materials. IFC does have entities to define specularity [1], but it is seldomly used or has meaningless default values. Therefore in the BIMserver no reference to material specularity is stored. Most building materials are purely diffuse, such as brick and plaster. I would propose to simply set the specularity to zero for all materials.

[1] http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcpresentationappearanceresource/lexical/ifcsurfacestylerendering.htm

**Comment by xeolabs** [comment]
Removed specular shading, set light sources to one ambient source plus a single directional light behind viewpoint. 

![screenshot from 2016-04-27 17 29 00](https://cloud.githubusercontent.com/assets/83100/14857727/9d97d626-0c9d-11e6-95f9-5c138db9ddb7.png)

![screenshot from 2016-04-27 17 28 35](https://cloud.githubusercontent.com/assets/83100/14857728/a12bb1cc-0c9d-11e6-9d99-53807bef105f.png)

**Comment by aothms** [comment]
Looks good to me :+1:
