### ISSUE TITLE
toggle transparancy

### ISSUE THREAD

**Issue by berlotti** [opensourceBIM/BIMsurfer-before2019#138]
remove the default transparent objects. This is BIM, not a game engine. Would be nice to toggle transparancy, but not by default.

**Comment by xeolabs** [comment]
Do you mean show all objects as opaque until they are made transparent?  Not sure what you mean by 'default' transparent objects.

**Comment by aothms** [comment]
Triangles should have transparency if and only if the data from IFC tells us so. 

If you have concerns about elements not being visible when navigating to them upon clicking in tree view. This can be made more intelligently later on, e.g orienting to a orientation that gives free sight to the element, or other approaches.

**Comment by aothms** [comment]
In the old scenejs based viewer we also didn't have perfect transparency as you had an additive blend mode I think to have some order independence, but opaque elements such as the walls were not rendered transparently.

![bimviews](https://cloud.githubusercontent.com/assets/1096535/14849671/a0d4fa5e-0c74-11e6-81f4-5a78936d4e79.png)

![bimsurferv2](https://cloud.githubusercontent.com/assets/1096535/14849674/a39f2b7e-0c74-11e6-8d42-3e302ba36920.png)

**Comment by xeolabs** [comment]
Objects are already only transparent only if IFC tells them so. 

I forced them to be transparent just for testing.
