### ISSUE TITLE
Auto aspect ratio for ortho scale

### ISSUE THREAD

**Issue by xeolabs** [opensourceBIM/BIMsurfer-before2019#139]
An ortho view volume may currently be set with

``` javascript
bimSurfer.setCamera({ type: "ortho", scale: [100,100,100] });
```

but that does not take into account the current canvas aspect ratio, potentially resulting in a squashed image.

Solution may be to constrain the scale X and Y to the same aspect ratio as the canvas (while leaving scale Z unconstrained).

**Comment by aothms** [comment]
Why are there three components for the scale now? I don't understand the z-scale?

How do we do this for perspective currently, do we have a `fovx` or `fovy` parameter? If so, I would copy that and have something like `scalex` or `-y`.

In Blender there is one ortho scale parameter that governs the scale of the largest axis based on aspect ratio. I'm also fine with that.

**Comment by xeolabs** [comment]
Yeah z-scale is not necessary. I'll with the single ortho scale parameter like Blender's.

**Comment by xeolabs** [comment]
OK so I did this :-

Now if you execute `bimSurfer.setCamera({ type : "ortho", scale: .1 })` in the console with the automatically-generated rendering test model loaded, the view will look like this:

![screenshot from 2016-05-04 15 13 11](https://cloud.githubusercontent.com/assets/83100/15015222/df87d3b6-120a-11e6-9e53-d98a356cfb60.png)

Note that the `scale` is `0.1` and that the test model is sized at 40x40x40 . @aothms is that `scale` value giving the sort of view volume size we expect?

**Comment by aothms** [comment]
In Blender, the scale argument relates to the "real world" size of the model. Meaning that if you set scale to 0.1, your view would at most encompass an element of 0.1 units big. To me that makes sense, not sure what magic it requires in your projection matrix.

**Comment by xeolabs** [comment]
No problem, I should be able to do it that way.

**Comment by xeolabs** [comment]
Fixed in https://github.com/opensourceBIM/BIMsurfer/commit/5225f81ee30f32f232f47eea1e109ffbd619e697
