### ISSUE TITLE
Uncaught RangeError: Invalid typed array length

### ISSUE THREAD

**Issue by xeolabs** [opensourceBIM/BIMsurfer-before2019#140]
Getting that error when loading various models in V2 from **bimsurfer_v2-bimserver-1.4**

![screenshot from 2016-05-05 21 43 31](https://cloud.githubusercontent.com/assets/83100/15055016/a18f3684-130a-11e6-9c63-35e7277446f6.png)

I tried with all the IFC files in the attached ZIP.

[2011-09-14-Duplex-IFC (2).zip](https://github.com/opensourceBIM/BIMsurfer/files/251093/2011-09-14-Duplex-IFC.2.zip)

**Comment by gstslxd** [comment]
similar error get when loading a ifc product.
![1](https://cloud.githubusercontent.com/assets/16719875/15113712/876883ca-1628-11e6-8124-d8604eadea3e.png)
