### ISSUE TITLE
An error breaks loading of IFC model

### ISSUE THREAD

**Issue by ilyakuznetsov** [opensourceBIM/BIMsurfer-before2019#148]
Hi! An error breaks loading of our test IFC model in BimsurferV2.
Error message:
 DataInputStreamReader.js?bust=1468304482895:94 Uncaught RangeError: Invalid typed array length
Debug-output:
Loading... (0/123)
BimSurfer.js?bust=1468304482895:169 Loading... (1/123)
BimSurfer.js?bust=1468304482895:169 Loading... (2/123)
BimSurfer.js?bust=1468304482895:169 Loading... (3/123)
BimSurfer.js?bust=1468304482895:169 Loading... (4/123)
BimSurfer.js?bust=1468304482895:169 Loading... (5/123)

Error occures in BimServerGeometryLoader._readObject.
geometryType of the data block, which causes the error, is 3.
 It  seems that the received data structure doesn't match the awaited.

Bimserver version 1.4

The same model can be loaded in bimviews (BimsurferV1).

Link to model: https://raw.githubusercontent.com/e-task/IFC-files/master/eTASK/MUC-xyz40.ARC.ifc

**Comment by rubendel** [comment]
BIMsurferV2 is only working on BIMserver 1.5 from now on because it's too hard to maintain compatibility for 2 versions of BIMserver.

**Comment by ilyakuznetsov** [comment]
thank you for the quick answer! but unfortunately I can't load it also from Bimserver 1.5
console output:
success ["Login successful", 5000]
Notifier.js?bust=2.0:25 info ["Login successful", 2000]
BimSurfer.js?bust=2.0:169 Loading... (0/122)
DataInputStreamReader.js?bust=2.0:55 Uncaught RangeError: Offset is outside the bounds of the DataView

**Comment by rubendel** [comment]
Which version of the BinarySerializer plugin are you using?

**Comment by ilyakuznetsov** [comment]
BinarySerializers (bundle) 0.0.14
