### ISSUE TITLE
question: When is the loading finished?

### ISSUE THREAD

**Issue by 9on** [opensourceBIM/BIMsurfer-before2019#149]
I have been playing with `V2` branch, and I'm having trouble trying to set different colors for all the elements. Since everything is async, i need to wait until the model is fully loaded.
Is there a way to know when it is ready?

would it be easier if i use `Master` branch, and try to define a setColor() function by my self?

thank you

**Comment by bhargavdave27** [comment]
Hi. I have been trying to get the V2 branch to work with BIM Server 1.5.x. Is that what you have got to work? If so, can you please let me know how?

**Comment by 9on** [comment]
> Hi. I have been trying to get the V2 branch to work with BIM Server 1.5.x. Is that what you have got to work?

My recommendation is, if you are going to work with the last commit of the `V2` branch, make sure you are using the last downloadable BIMServer . When you refer to `1.5.x`, that little "x", was **very** important to me. 

> If so, can you please let me know how?

Make sure you are loading the required javascript libraries correctly.
After that, make sure you are logging in correctly.
After that, make sure you are loading the correct model (poid and roid).

... or at least that is what has been working for me.

**Comment by bhargavdave27** [comment]
Thanks! I have been trying to work with the latest BIMServer. Will try to
follow these steps.The POID and ROID are fine and so are te login details,
but the viewer page doesn't show anything.

**Comment by rubendel** [comment]
This seems to be fixed in https://github.com/Bastien--/BIMsurfer/commit/2329b3be26d5d8e0e0a19f3763d9f8afc9f254e1
