### ISSUE TITLE
Always have sun(light) behind the camera

### ISSUE THREAD

**Issue by berlotti** [opensourceBIM/BIMsurfer-before2019#15]
When turning the model, the shadowside comes to the front. It's pretty dark....
Always having the sun on the back of the camera makes sure that the viewable area is always light.

**Comment by rehno-lindeque** [comment]
Thanks, I think we should just add an ambient light first to get the intensity of the shadows right... then re-evaluate

**Comment by rehno-lindeque** [comment]
Requires a small change to SceneJS
https://groups.google.com/d/topic/scenejs/fY1X5TJuqCY/discussion

**Comment by rehno-lindeque** [comment]
See also issue #6 - let's evaluate whether this is necessary once ambient light is fixed up
