### ISSUE TITLE
Only render when camera moves?

### ISSUE THREAD

**Issue by bastienmenis** [opensourceBIM/BIMsurfer-before2019#151]
BIMsurfer v2 constantly use 100% of the CPU as the rendering loop is always active. Can the rendering be paused when the camera is not moving and the model is not modified? Not sure whether this should be a feature of BIMsurfer or xeoEngine. 

BIMsurfer v1 seems to operated differently and only run use high CPU when I move the camera.

**Comment by xeolabs** [comment]
Just fixed this in xeoEngine (https://github.com/xeolabs/xeoengine/commit/74dd1cdbfb3dc87c5fce4d2640ed8c7666a608ab) and BIMSurfer (https://github.com/opensourceBIM/BIMsurfer/commit/a352e67490d0a24ab917b74302f8c651d39e70a0)

**Comment by bastienmenis** [comment]
Works perfectly, thanks!
