### ISSUE TITLE
loadBimServerApi is not defined

### ISSUE THREAD

**Issue by mobiniustechnologies** [opensourceBIM/BIMsurfer-before2019#153]
HI,

I tried to do the basic installation. However I am unable to login. It says loadBimServerApi undefined. Could you please assist me. Seems to be some files are still missing ?
![birm-surfer-error-login](https://cloud.githubusercontent.com/assets/1502539/18861683/c5018674-84a4-11e6-9570-9a43f3dcabef.png)

**Comment by rubendel** [comment]
V1 is not maintained anymore, we will change to V2 today
