### ISSUE TITLE
example1.html is not working because of missing files ?

### ISSUE THREAD

**Issue by GreenUtil** [opensourceBIM/BIMsurfer-before2019#156]
script type="text/javascript" src="js/bimserverapibootstrap.js">
script type="text/javascript" src="js/String.js">
script type="text/javascript" src="js/utils.js">

These files are missing in the Git repository, is that correct ?

**Comment by rubendel** [comment]
The example had been broken for a long time, should have removed it earlier. For an example of BIMsurfer V1, have a look at BIMvie.ws.
