### ISSUE TITLE
Idea: XRay viewing mode?

### ISSUE THREAD

**Issue by xeolabs** [opensourceBIM/BIMsurfer-before2019#162]
When navigating to objects with the explorer tree UI, we often end up looking at the object while it is occluded by something, such as a wall. If we were to have an 'X-ray' mode then we could make the currently selected objects colored, while unselected objects appear grey and transparent (really desaturated, like soft tissue in an xray image). Selected transparent objects would still appear transparent and colored.  The X-ray mode would be able to be toggled on and off, so would be optional.

It's easy to do - any thoughts?

**Comment by berlotti** [comment]
This is patented by vectorworks. Not sure what the implications are when we implement it.
