### ISSUE TITLE
Models are not rendering in BIMsurfer demo

### ISSUE THREAD

**Issue by przemwo** [opensourceBIM/BIMsurfer-before2019#167]
Hi,
I have two .ifc models A and B ([A.zip](https://github.com/opensourceBIM/BIMsurfer/files/541452/A.zip), [B.zip](https://github.com/opensourceBIM/BIMsurfer/files/541454/B.zip))
I wanted to use [BIMsurfer demo](https://github.com/opensourceBIM/BIMsurfer/blob/master/demo/example_BIMServer.html) to display both of them.
Model A is rendering great.
But there is a problem with model B. It is not rendering at all.

I get the same results when I try to user **BIMserver (v. 1.5.60)** admin viewer (/apps/bimviews).
Model A is rendering, B is not.

But with **BIMserver v. 1.4.0-FINAL-2015-11-04** in the admin viewer both models are rendering fine.

Do you have any idea what could be a problem here?

**Comment by xeolabs** [comment]
Any errors in the JS console?
