### ISSUE TITLE
Camera position change

### ISSUE THREAD

**Issue by RicoLiu** [opensourceBIM/BIMsurfer-before2019#168]
I try to change camera position.
Code is here(GeometryLoader.js):

`var eye = { x: 20, y: 20, z: 20 };`

But it doesn't seem to work,Where do I need to modify anything else?

**Comment by xeolabs** [comment]
Take a look at [usage.md](https://github.com/opensourceBIM/BIMsurfer/blob/master/USAGE.md#camera).
