### ISSUE TITLE
Mysterious box artifact 

### ISSUE THREAD

**Issue by xeolabs** [opensourceBIM/BIMsurfer-before2019#171]
A mysterious grey box appears near the center of the Schependomlaan example.

![screenshot from 2016-11-24 16 42 38](https://cloud.githubusercontent.com/assets/83100/20604127/193aa2aa-b265-11e6-8c87-3c327eabd0f8.png)

**Comment by xeolabs** [comment]
This object appears to be loaded as part of the model, ie. not a "helper element" created by xeogl :  

- the geometry ID is "1574635354"
- in the viewer the object ID is "11665411:3296920062"
- so object ID is 3296920062
- geometry ID is 1574635354
- if you click on it, the "IfcBuildingElementProxy" info panel shows name "ROOT nulpunt".

@rubendel / @aothms could this be a sort of "null object" in the model?

**Comment by aothms** [comment]
Ha well yeah this is a coordination trick people sometimes you in IFC file to explicitly mark the origin so that it is easier to see whether different discipline models align. Nothing to worry about.
