### ISSUE TITLE
Selection picking highlighting wrong elements

### ISSUE THREAD

**Issue by aothms** [opensourceBIM/BIMsurfer-before2019#172]
![selection](https://cloud.githubusercontent.com/assets/1096535/20595058/c656916a-b238-11e6-909f-fadee1e2a82e.gif)

**Comment by xeolabs** [comment]
For this particular element, could you post a screenshot showing the correct element highlighted? Would make it faster to verify the fix. I'm assuming that the little blus strip on the ground is not a "fund_strook".. Cheers

**Comment by xeolabs** [comment]
Sorry, I'm trying to reproduce this bug but I really can't see where selection is not correct. So far every element I select in the tree UI seems to be correctly appearing in the info panel, and clicking on that object shows the same info in that panel and selects the same node in the tree. Even the screen capture shows the "fund_strook" element as selecting correctly, which works the same for me..

**Comment by aothms** [comment]
Somehow my comment didn't come through. This turned out to be duplicate of #173. The overlay had shifted because of the type visibility indicator spanning multiple lines.
