### ISSUE TITLE
User input overlay positioning not updated

### ISSUE THREAD

**Issue by aothms** [opensourceBIM/BIMsurfer-before2019#173]
We cannot assume that the canvas holds a static position on the HTML page. In the case of the example demo the type visibility control can grow based on the amount of types in the model. But in general we cannot assume the canvas has a fixed position.

* Why is this separate overlay div necessary?
* If it really is, can we position it normally?
* If not, can you sync its position with the canvas?

![overlay](https://cloud.githubusercontent.com/assets/1096535/20595966/802c2214-b23c-11e6-97de-f82c3fcedc61.gif)

**Comment by xeolabs** [comment]
Yeah it should synch with the canvas. I'll see if fixing that helps. The overlay div is so that xeogl components can potentially involve non-clickable HTML elements, where the overlay allows normal camera input to avoid hitting them.

**Comment by aothms** [comment]
Seems to work well. Are you confident the `OffsetParent`,`-Top` & `-Left` will mostly be a reasonable indicator of the positioning, or should it be made recursive? It seems it could be for the `OffsetParent` not to be the document body and then canvas can move without changes in `OffsetTop` & `-Left`.

**Comment by xeolabs** [comment]
Now that you mention that, I should make it recursive, to be fully robust, since the overlay is positioned "absolute". I'll do that sometime in the near future though, if this fix is enough for this BIMSurfer iteration.
