### ISSUE TITLE
model.queryNew() undefined in BIMSurferModel.js 

### ISSUE THREAD

**Issue by xeolabs** [opensourceBIM/BIMsurfer-before2019#175]
Loading "Schependomlaan - Single" from thisisanexperimentalserver.com, on example_BIMServer.html,  model.queryNew() is undefined in BIMSurferModel.js, stops things loading:

![screenshot from 2016-11-24 13 03 34](https://cloud.githubusercontent.com/assets/83100/20597929/c499cf6e-b246-11e6-84c1-a1986d445ccc.png)

**Comment by rubendel** [comment]
In my version here of BimServerModel.js, this has already been renamed from queryNew to query (changed one month ago)

**Comment by xeolabs** [comment]
Yeah I just realised I was running an old project.
