### ISSUE TITLE
Don't show yellow dot when dbl-clicking to set pivot

### ISSUE THREAD

**Issue by xeolabs** [opensourceBIM/BIMsurfer-before2019#176]

**Comment by aothms** [comment]
Why this? I think it is ok as is. What I would change is that the yellow dot reappears when the user is orbiting. Would this be possible?

**Comment by xeolabs** [comment]
Oh - I just recalled someone saying get rid of it. I'll keep it then. Sure, I'll make it appear while orbiting, and also scale it in proportion to (eye->target) distance.
