### ISSUE TITLE
Merge master into gh-pages?

### ISSUE THREAD

**Issue by xeolabs** [opensourceBIM/BIMsurfer-before2019#180]
* Demo examples will be available to view online.
* Current gh-pages branch is at least 4 years out of date.
* Would help with crowd-testing, can send links to people to check on their setups.

**Comment by aothms** [comment]
Pages are setup to be rendered from the master branch: http://opensourcebim.github.io/BIMsurfer/ 

If @berlotti or @rubendel do not object I will remove the old gh-pages branch.
