### ISSUE TITLE
BIMSurfer without BIM Server

### ISSUE THREAD

**Issue by ghost** [opensourceBIM/BIMsurfer-before2019#187]
Is there any way I can use BIMSurfer without BIMServer for displaying 3d bim models? I want to create a simple and generic server and use it instead of BimServer. 

Thanks.

**Comment by aothms** [comment]
The new version of the BimSurfer, i.e. the current master branch, has support for loading glTF models. You can get glTF models for example by using IfcConvert [1] to convert to Collada and then use the official collada2gltf converter [2].

[1] http://ifcopenshell.org/ifcconvert.html
[2] https://github.com/KhronosGroup/COLLADA2GLTF/wiki
