### ISSUE TITLE
Model loaded but nothing is shown

### ISSUE THREAD

**Issue by raindog** [opensourceBIM/BIMsurfer-before2019#192]
Hi,
I'm trying to visualize the model inside [this](https://github.com/opensourceBIM/BIMsurfer/files/770621/Prova.1100.ifc.zip) ifc file. 
The model is loaded  correctly, but nothing is displayed on the 3D view. 
On the javascript console there are no errors reported.

Can you give me some hints for facing the issue?
The file contains empty elements name. Could this be a problem?
I'm working with the https://github.com/opensourceBIM/BIMserver/releases/tag/parent-1.5.65 release.

Thank you

**Comment by rubendel** [comment]
Can you try this release with the latest versions of plugins? https://github.com/opensourceBIM/BIMserver/releases/tag/parent-1.5.67

Previous versions did not calculate the bounding box the right way, which (for some models) resulted in models that loaded in BIMvie.ws, but would be out of view.

The models you sent is working in my version.

**Comment by raindog** [comment]
Ruben, let me do other tests but with the  1.5.67 release I can see nothing on the 3d view, even trying to load files I'm sure they worked with previous versions.
[Here](https://github.com/opensourceBIM/BIMsurfer/files/770815/Prova_computo.ifc.zip) there is another file not working with the 65 nor with the 67 version.

With this version, the "model data successfully loaded" notification appears as soon as I click on the "root eye" but no progress bar is displayed. This behaviour is shown for every file I loaded so far.

I've just noticed that when I switch i.e. from the project tab to the 3D tab, this error show up on the js console:

````
   Uncaught TypeError: promise.done is not a function

   at TabChanger2.changeTab (bimviews.js?_v=0.0.71:15111)

    at RightPanel.showThreeD (eval at globalEval (bimviews.js?_v=0.0.71:338), <anonymous>:31:21)

    at HTMLLabelElement.eval (eval at globalEval (bimviews.js?_v=0.0.71:338), <anonymous>:56:5)

    at HTMLLabelElement.dispatch (bimviews.js?_v=0.0.71:4732)

    at HTMLLabelElement.elemData.handle (bimviews.js?_v=0.0.71:4544)
````
I don't know if this could be relevant.

**Comment by raindog** [comment]
Hi @rubendel, could you please point me to a working combination of bimserver and plugin version on the 1.5 branch?

**Comment by raindog** [comment]
Maybe I found the source of my issue of not being able to visualize the model on the  1.5.67 release. After checking in an ifc file, on the error log  I've found the following rows:

```
16:11:40 ERROR [pool-10-thread-2]: Version mismatch: Plugin version IfcOpenShell-0.5.0-dev-2 does not match IfcOpenShell version IfcOpenShell-0.5.0-dev (IfcGeomServerClient.java:49) 
16:11:40 ERROR [pool-10-thread-2]:                                                                                  (StreamingGeometryGenerator.java:380) 
java.lang.NullPointerException: null
	at org.ifcopenshell.IfcGeomServerClient$Command.write(IfcGeomServerClient.java:104)
	at org.ifcopenshell.IfcGeomServerClient.loadModel(IfcGeomServerClient.java:70)
	at org.ifcopenshell.IfcOpenShellModel.<init>(IfcOpenShellModel.java:69)
	at org.ifcopenshell.IfcOpenShellEngine.openModel(IfcOpenShellEngine.java:73)
	at org.bimserver.StreamingGeometryGenerator$Runner.run(StreamingGeometryGenerator.java:191)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I have however installed the ifcopenshellplugin-0.5.19 version.

**Comment by rubendel** [comment]
What OS are you on and does it use 32 or 64 bit?

**Comment by raindog** [comment]
I can reproduce the thing on Mac OSX 10.11.6 and MacOS 10.12.3, so x64, with the latest jdk (1.8.121). The funny thing is that in the last two days I haven't been able to connect to the plugin repository via the "installed plugin bundle" to try an older plugin version.

Another strange log line during the installation process is this:
````
org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.opensourcebim:bimserverapi:properties:version:0.0.108 from/to given (central (http://central.maven.org/maven2, default, releases+snapshots)): Cannot access central (http://central.maven.org/maven2, default, releases+snapshots) with type default using the available connector factories: BasicRepositoryConnectorFactory
````
This for every plugin set up during the installation.

@rubendel I would like to thank you for the time spent trying to investigate this issue, that is probably only  a my own thing. I had a little demo with this server yesterday, so the urgence on this thing is decreased greatly now ;-) I can wait for the next dev release and see if this thing automagically disappears. Again, thank you.

**Comment by rubendel** [comment]
I also noticed the maven repository being a little slower than usual. Maybe we should setup our own mirror at some point. I don't have access to an OSX machine at the moment so I can't really test IfcOpenShell on OSX.

**Comment by dbarthelemy** [comment]
Hi @rubendel , I am experiencing the exact same issue running on Mac OS X 10.11.5 / Java 1.8.0_121... 3D render shows nothing on Google Chrome or Safari.

I am using a fresh clone of the BIMserver release tag parent-1.5.67 doing the standard setup (commenting out the portion of code from LocalDevBimServerStarter which skip the setup stage).

IFC check-in goes well according to the web front but in the Eclipse console several errors are listed:
```
Version mismatch: Plugin version IfcOpenShell-0.5.0-dev-2 does not match IfcOpenShell version IfcOpenShell-0.5.0-dev (IfcGeomServerClient.java:49) 
```

Also for info, several errors during initial plugin installation are in the console:
```
PluginInterface.installPluginBundle]:                                                                                  (MavenPluginLocation.java:385) 
java.text.ParseException: Unparseable date: "${timestamp}
```

Also one error linked to Maven:
```
org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.opensourcebim:console:properties:version:0.0.4 from/to given (central (http://central.maven.org/maven2, default, releases+snapshots)): Cannot access central (http://central.maven.org/maven2, default, releases+snapshots) with type default using the available connector factories: BasicRepositoryConnectorFactory
```

The same IFC model was working just fine on my previous environment based on parent-1.5.65, but after upgrading all installed plugins this one no longer works.

**Comment by dbarthelemy** [comment]
By downgrading IfcOpenShellPlugin to 0.5.17 and using the legacy serializer (not the Streaming one) during the model Checkin process... 3D rendering works again.
This does not fix the root cause of this issue, but at least is a good enough work-around for the time being.

**Comment by rubendel** [comment]
There are several issues going on here:
1. The IfcOpenShell plugin build did not include OSX binaries, so those are not updated, and that causes the version error "Version mismatch: Plugin version IfcOpenShell-0.5.0-dev-2 does not match IfcOpenShell version IfcOpenShell-0.5.0-dev (IfcGeomServerClient.java:49)". I don't know when those binaries for OSX will be available. So downgrading the IfcOpenShell plugin sounds like the best plan for OSX for now.
2. Older plugins did not include a version.properties file, or a version.properties file that had not been replaced with a release date. It would be interesting to know which plugin is causing this error ("Unparseable date: "${timestamp}") so I can update it (I cannot however edit already released plugins).
3. As stated elsewhere (or in this issue) there is a problem with older versions of BIMserver downloading plugins that are too new (not binary compatible), that issue has not been resolved yet.
4. The "org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.opensourcebim:console:properties:version:0.0.4 from/to given (central (http://central.maven.org/maven2, default, releases+snapshots)): Cannot access central (http://central.maven.org/maven2, default, releases+snapshots) with type default using the available connector factories: BasicRepositoryConnectorFactory" relates to point 2.

So far I have identified "Console" as a project that needs to be updated to include a version.properties file, if you find more, please let me know.

**Comment by raindog** [comment]
So, related to point 1, which IfcOpenShell version can I use? Wich is the latest IfcOpenShell version providing binaries for OSX? I tried all the versions back to 0.5.15... and I still have a blank 3D section after the checkin.
If I remember correctly the latest packaged bimserver version without this issue was the 1.5.64, I don't know if this can help.

**Comment by rubendel** [comment]
0.5.17 should work on OSX I think, but I have not tested on OSX in years... If you can post the errors you get with that version that would be usefull. Be sure to checkin again.

**Comment by raindog** [comment]
Ruben,  attached here you can find the bimserver logs for OSX and WIN with the following setup:
. OSX - IfcOpenShell 0.5.17 here: [OSX-bimserver.log.zip](https://github.com/opensourceBIM/BIMsurfer/files/816382/OSX-bimserver.log.zip)
. WIN -  IfcOpenShell 0.5.17 here: [WIN-bimserver.log.zip](https://github.com/opensourceBIM/BIMsurfer/files/816383/WIN-bimserver.log.zip)
On OSX no error appears on the browser console.

**Comment by rubendel** [comment]
Thanks for that. So on windows, you should use the latest version. Unfortunately the older version does not seem to work on OSX with the newest version of BIMserver. I'll ask the developer os IfcOpenShell to build a OSX version.

**Comment by raindog** [comment]
You're welcome, and thanks to you too!

**Comment by rubendel** [comment]
ETA for a working OSX build is in one week

**Comment by raindog** [comment]
Hi @rubendel, any news about the OSX build?

**Comment by rubendel** [comment]
Sorry, haven't gotten it yet

**Comment by rubendel** [comment]
A new version is available. I have not been able to test it, but the OSX executable is updated so I think it will work. It can take up to 24 hours before your BIMserver will find this new version (0.5.22).

**Comment by raindog** [comment]
Thank you so much Ruben, I'll try it as soon as possible and II'll let you know how it's going.

**Comment by raindog** [comment]
I've done some (really) quick tests loading a couple of models, and it seems to be ok!

**Comment by rubendel** [comment]
Great, thanks for the feedback
