### ISSUE TITLE
how to rotate 3d views in bimsurfer

### ISSUE THREAD

**Issue by urlpha** [opensourceBIM/BIMsurfer-before2019#194]
hi
i was successfully run bimsurfer and get 3d views in pc web browser, and the 3d view can spin using mouse.
now , i want to use mobilephone web browser to do the same thing, but it only can show 3d view ,i can't spin the 3d model as in pc web browser.

i checked the #177  but it does not work in my android firefox browser.

so, how to rotate/spin 3d views in mobilephone web browser? does the bimsurfer js support?

**Comment by dzerzhinsky** [comment]
Hi，Has this problem been solved?

**Comment by rubendel** [comment]
Mobile is not supported, and we don't plan to, contributions on this front are welcome.
