### ISSUE TITLE
I would like to ask under the bimsurfer problem

### ISSUE THREAD

**Issue by liufenghiee** [opensourceBIM/BIMsurfer-before2019#195]
Hello, I am a software engineer at an Internet company in Hangzhou, China, and our company recently used bimserver,
We have deployed bimserver and bimview.ws, I use the chrome browser to open and upload the model,
We found that the model is a one-time loading completed, I would like to ask whether the support of the model bimserver delay loading, that is
When I roam in the model, while the side of the roaming side of the load, only to load the direction of the roaming people within 10 meters model components.
Also I would like to ask,  bimserver whether to support the model roaming in the ipad and preview, I found iphone6 mobile phone and ipad roaming, the model has not shown the phenomenon.

**Comment by xiaohujing** [comment]
你好，你的bimsurfer是单独部署的还是bimserver下载的插件

**Comment by dzerzhinsky** [comment]
Will the mobile terminal be loaded? Is it possible to drag and drop rotation?

**Comment by rubendel** [comment]
Mobile is not supported, contributions on this are welcome.
