### ISSUE TITLE
Viewport should cover the entire screen (except for the snapshots fold)

### ISSUE THREAD

**Issue by rehno-lindeque** [opensourceBIM/BIMsurfer-before2019#2]
The active working area for the mouse should be the entire screen (and must not be hampered by e.g. help icons etc)
In addition the canvas should be either fullscreen or 1024x1024 depending on the performance setting in the top menu

(It is said that full screen canvas can be slow on slow machines - so giving people the option of resizing... should test this hypothesis first though)

**Comment by rehno-lindeque** [comment]
Viewport is now properly fullscreen, but mouse is still affected by hovering over "help" elements drawn over the canvas

**Comment by berlotti** [comment]
fixed
