### ISSUE TITLE
Internet Explorer 11 does not work with the VCMP and BIM Viewer

### ISSUE THREAD

**Issue by darrenmulligan** [opensourceBIM/BIMsurfer-before2019#213]
Hi Im having issues using the VCMP.eu on IE11  and also on VRM Technology's site viewing the model on the Viewer, is this a known issue with IE11?

Thanks

Darren

**Comment by rubendel** [comment]
IE11 is not supported, nor is any other version of IE.

**Comment by darrenmulligan** [comment]
Ok thanks for the response.
