### ISSUE TITLE
Unable to load BIM Server Page and Log in.

### ISSUE THREAD

**Issue by RichWBHO88** [opensourceBIM/BIMsurfer-before2019#215]
Hi Folks

Please can you tell me if the Open source BIM Server is compatible Internet Explorer ?

Cannot find it in the documentation and the BIMViews applet does not load in IE.

Running the Java Based BIM version 1.5.85.

Thanks.

**Comment by rubendel** [comment]
IE is not supported, it's not an applet...

**Comment by RichWBHO88** [comment]
Thanks Ruben.
