### ISSUE TITLE
error BimServerGeometryLoader._readStart

### ISSUE THREAD

**Issue by halmsx** [opensourceBIM/BIMsurfer-before2019#219]
hi guys. im having error like below

`BimServerGeometryLoader._readStart | @ | BimServerGeometryLoa…t=1508951662763:212`

ive looked at the source but dont understand what it is referring to. what is protocolVersion?

can anyone help to explain to me? thanks in advance

**Comment by rubendel** [comment]
Protocol version indicates the version of the protocol used... If it says the protocol version is not right, you need to upgrade either end (BinarySerializer or BIMsurfer) of the connection.

**Comment by halmsx** [comment]
hi. something must went wrong somewhere. i downloaded the same version again and is working again. thanks
