### ISSUE TITLE
BimServerApi is not a constructor

### ISSUE THREAD

**Issue by alilouchka** [opensourceBIM/BIMsurfer-before2019#239]
Hi, 

I'm trying to test BimSurfer in order to display ifc file in my browser.
this is my code : 

![2018-02-01_10h29_32](https://user-images.githubusercontent.com/26714480/35671155-d37250ac-073a-11e8-838c-54dd6b645c18.png)

I used the same code shown if BimSurfer but i got thirs error when I try to load my file : 
![2018-02-01_10h25_18](https://user-images.githubusercontent.com/26714480/35670947-3a8738a8-073a-11e8-9eda-35b9c72d1d7f.png)

Help please ! : )

**Comment by JackLeeMing** [comment]
<img width="510" alt="qq20180207-092358 2x" src="https://user-images.githubusercontent.com/8730975/35893350-a63f93c6-0be8-11e8-8d17-032c52bcf15b.png">

maybe this can help you.

**Comment by JackLeeMing** [comment]
<img width="964" alt="qq20180207-100536 2x" src="https://user-images.githubusercontent.com/8730975/35894602-8ca746e2-0bee-11e8-9c68-5fe4857aa213.png">
<img width="523" alt="qq20180207-100557 2x" src="https://user-images.githubusercontent.com/8730975/35894606-9367ae72-0bee-11e8-838d-5608378fb3f4.png">

**Comment by JackLeeMing** [comment]
<img width="752" alt="1" src="https://user-images.githubusercontent.com/8730975/35894687-f899fcc8-0bee-11e8-9b69-073f5f3cc1a2.png">
<img width="523" alt="qq20180207-100557 2x" src="https://user-images.githubusercontent.com/8730975/35894694-0049d790-0bef-11e8-9ca9-7ea4a2eb08f7.png">

**Comment by alilouchka** [comment]
Thank you @JackLeeMing !
  
Where did you add the function  "last this._loadFromServer" please ? 
Can you send me  the complete code please ? 

Thanks :=)

**Comment by JackLeeMing** [comment]
<img width="679" alt="1" src="https://user-images.githubusercontent.com/8730975/36649333-44dafab4-1ad7-11e8-9b24-86776d0bdda7.png">
<img width="571" alt="2" src="https://user-images.githubusercontent.com/8730975/36649336-4786c676-1ad7-11e8-97db-ea632b80856d.png">
<img width="1088" alt="31" src="https://user-images.githubusercontent.com/8730975/36649339-4a0178d8-1ad7-11e8-97fb-c0966980368c.png">
<img width="876" alt="32" src="https://user-images.githubusercontent.com/8730975/36649340-4d2b8cf6-1ad7-11e8-8ceb-709dfde944a6.png">
<img width="944" alt="4" src="https://user-images.githubusercontent.com/8730975/36649341-4f4174c4-1ad7-11e8-9acf-6ed68e1e006e.png">

**Comment by mateuszkib** [comment]
Did you manage to fix this error? Because I have the same problem.

**Comment by halmsx** [comment]
`<!doctype html>
<html>

<head>
  <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
  <meta content="utf-8" http-equiv="encoding">
  <base href="/sites/all/libraries/bimsurfer/bimsurfer/" />
  <title>BIM Viewer 1</title>

  
  <link rel="stylesheet" href="./lib/old/css/style.css"/>
  <link rel="stylesheet" href="./lib/old/css/apiref.css"/>
  <link rel="stylesheet" href="./lib/old/css/layout.css"/>
  <link rel="stylesheet" href="./lib/old/css/tree.css"/>
  <link rel="stylesheet" href="./lib/old/css/metadata.css"/>

  

  
  

  <script type="text/javascript" src="./lib/old/utils.js"></script>
  <script type="text/javascript" src="./lib/old/bimsurfer/lib/require.js"></script>

  <script type="module">
    var bimserverapi;
    var address = 'http://localhost:8101';
    var addressapi = address + '/apps/bimserverjavascriptapi/';
    var apiVersion = new Date().getTime();
    var roid;

    var p = new Promise(function(resolve, reject){
	        var str = "import(\"http://localhost:8101/apps/bimserverjavascriptapi/bimserverclient.js?_v=" + apiVersion + "\").then((bimserverapi) => {	window.BimServerClient = bimserverapi.default; window.BimServerApiPromise = bimserverapi.BimServerApiPromise; resolve(bimserverapi);});";
			eval(str);
    });

    p.then(() => {
      
      require([
        "lib/old/bimsurfer/src/BimSurfer",
        "lib/old/bimsurfer/src/BimServerModelLoader",
        "lib/old/bimsurfer/src/StaticTreeRenderer",
        "lib/old/bimsurfer/src/MetaDataRenderer",
        "lib/old/bimsurfer/lib/domReady!",
        "lib/old/bimsurfer/src/Utils"
      ], function (BimSurfer, BimServerModelLoader, StaticTreeRenderer, MetaDataRenderer, Utils) {

        var username = "node@nbes.my", password = "klasklas";
        var client = new BimServerClient(address);

        client.login(username, password, function (res) {
          // console.log(client.token)

          /**
           * starts bimsurfer
           */
          var bimSurfer = new BimSurfer({
            domNode: "viewerContainer"
          });

          client.call("ServiceInterface", "getProjectByPoid", {
            poid: QueryString.poid
          }, function (project) {
            roid = project.lastRevisionId
            console.log(roid)

            bimSurfer.on("loading-started", function(){
              document.getElementById("status").innerHTML = "Loading...";
            });

            window.bimSurfer = bimSurfer;

            bimSurfer.load({
              bimserver: address,
              token: client.token,
              poid: QueryString.poid,
              roid: roid,
              schema: "ifc2x3tc1" // < TODO: Deduce automatically
            }).then(function (model) {
              /* model.getTree().then(function (tree) {

              }) */
            })

          });

        });        
      });
    });
  </script>

</head>

<body style="margin: 0; padding: 0">

  <div id="maincontainer">
    <div id="topsection">
      
      <div id="typeSelector">
        <div>&nbsp;</div>
      </div>
    </div>
    <div id="contentwrapper">
      <div id="colmid">
        <div id="colright">
          <div id="col1wrap">
            <div id="col1pad">
              <div id="viewerContainer">
              </div>
            </div>
          </div>
          <div id="treeContainer" class="bimsurfer-static-tree">
          </div>
          <div id="dataContainer" class="bimsurfer-metadata">
          </div>
        </div>
      </div>
    </div>
    
  </div>
  <div id="status"></div>
  
  <div id='apirefContainer'>
    <h1>API Reference</h1>
  </div>

</body>
`

**Comment by halmsx** [comment]
``<!doctype html>
<html>

<head>
  <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
  <meta content="utf-8" http-equiv="encoding">
  <base href="/sites/all/libraries/bimsurfer/bimsurfer/" />
  <title>BIM Viewer 1</title>

  
  <link rel="stylesheet" href="./lib/old/css/style.css"/>
  <link rel="stylesheet" href="./lib/old/css/apiref.css"/>
  <link rel="stylesheet" href="./lib/old/css/layout.css"/>
  <link rel="stylesheet" href="./lib/old/css/tree.css"/>
  <link rel="stylesheet" href="./lib/old/css/metadata.css"/>

  

  
  

  <script type="text/javascript" src="./lib/old/utils.js"></script>
  <script type="text/javascript" src="./lib/old/bimsurfer/lib/require.js"></script>

  <script type="module">
    var bimserverapi;
    var address = 'http://localhost:8101';
    var addressapi = address + '/apps/bimserverjavascriptapi/';
    var apiVersion = new Date().getTime();
    var roid;

    var p = new Promise(function(resolve, reject){
	        var str = "import(\"http://localhost:8101/apps/bimserverjavascriptapi/bimserverclient.js?_v=" + apiVersion + "\").then((bimserverapi) => {	window.BimServerClient = bimserverapi.default; window.BimServerApiPromise = bimserverapi.BimServerApiPromise; resolve(bimserverapi);});";
			eval(str);
    });

    p.then(() => {
      
      require([
        "lib/old/bimsurfer/src/BimSurfer",
        "lib/old/bimsurfer/src/BimServerModelLoader",
        "lib/old/bimsurfer/src/StaticTreeRenderer",
        "lib/old/bimsurfer/src/MetaDataRenderer",
        "lib/old/bimsurfer/lib/domReady!",
        "lib/old/bimsurfer/src/Utils"
      ], function (BimSurfer, BimServerModelLoader, StaticTreeRenderer, MetaDataRenderer, Utils) {

        var username = "node@nbes.my", password = "klasklas";
        var client = new BimServerClient(address);

        client.login(username, password, function (res) {
          // console.log(client.token)

          /**
           * starts bimsurfer
           */
          var bimSurfer = new BimSurfer({
            domNode: "viewerContainer"
          });

          client.call("ServiceInterface", "getProjectByPoid", {
            poid: QueryString.poid
          }, function (project) {
            roid = project.lastRevisionId
            console.log(roid)

            bimSurfer.on("loading-started", function(){
              document.getElementById("status").innerHTML = "Loading...";
            });

            window.bimSurfer = bimSurfer;

            bimSurfer.load({
              bimserver: address,
              token: client.token,
              poid: QueryString.poid,
              roid: roid,
              schema: "ifc2x3tc1" // < TODO: Deduce automatically
            }).then(function (model) {
              /* model.getTree().then(function (tree) {

              }) */
            })

          });

        });        
      });
    });
  </script>

</head>

<body style="margin: 0; padding: 0">

  <div id="maincontainer">
    <div id="topsection">
      
      <div id="typeSelector">
        <div>&nbsp;</div>
      </div>
    </div>
    <div id="contentwrapper">
      <div id="colmid">
        <div id="colright">
          <div id="col1wrap">
            <div id="col1pad">
              <div id="viewerContainer">
              </div>
            </div>
          </div>
          <div id="treeContainer" class="bimsurfer-static-tree">
          </div>
          <div id="dataContainer" class="bimsurfer-metadata">
          </div>
        </div>
      </div>
    </div>
    
  </div>
  <div id="status"></div>
  
  <div id='apirefContainer'>
    <h1>API Reference</h1>
  </div>

</body>
``

**Comment by halmsx** [comment]
the latest example file from master is now working!
