### ISSUE TITLE
How I can load IFC models to BimServer

### ISSUE THREAD

**Issue by mateuszkib** [opensourceBIM/BIMsurfer-before2019#244]
Hi. I have a server running in local machine. I have a question : How can to load a ifc model into BIMserver http://localhost:8082/apps/bimviews/?page=Projects  ?.

**Comment by rubendel** [comment]
Using BIMvie.ws (which is not BIMsurfer): Create a project, click on the little black triangle next to the project name and select "Checkin"

**Comment by mateuszkib** [comment]
Ok, thanks. I'm trying to add the ifc model, but the bar comes to an end and stands still... 
I also have a different problem, I get an error : BimServerApi is not a constructor
What can be caused by this error?

**Comment by rubendel** [comment]
If you tell us which version you are using we might be able to help, also, are there any errors in the logfile?

**Comment by mateuszkib** [comment]
I use version : 1.5.100 . Ok, I download IFC models from IFC-files, this model is : Schultz_Residence.ifc . 

The model has been added correctly to the project. But I have a error in console : 
![screen2](https://user-images.githubusercontent.com/26137138/38974952-48994cfc-43ac-11e8-81a6-746de6544331.png)

And this is my code: 
![screen1](https://user-images.githubusercontent.com/26137138/38975007-748cdff4-43ac-11e8-9878-4eae687627e9.png)

What I did wrong ?

**Comment by rubendel** [comment]
Are you loading the index.html of BIMsurfer from disk instead of from a webserver?

**Comment by mateuszkib** [comment]
Yes, I load index.html from disk. How can I loading from a webserver?

**Comment by likekaede** [comment]
BIMVewer       where is  this one ？

**Comment by rubendel** [comment]
I don't know what you mean
