### ISSUE TITLE
Some problem checking the examples

### ISSUE THREAD

**Issue by orashkenazi** [opensourceBIM/BIMsurfer-before2019#250]
Maybe im missing something.

In short.
1. I run my BIM server on localhost:8082, using the JAR file of latest version.
2. I cloned BIMSurfer git, running it on 8080.
3. i modified the index.html username and pass in the place of the localhost:8082 in the try block of loadBimServerApi.

4. trying to run it. its loading the project from my bim server quite good. clicking on it -> it fails and index.html as it try to navigate to "bimsurfer2/docs/.../../....."
5. as there is not this folder (bimsurfer2) in my folder, and i see the relevent file exist under docs in the root folder, i change the address href on the line 56 to "./docs/......example_BIMServer.html?address=" + .....

6. i try to run again, now i get  the loading spinner but nothing happens. i check console and i see everywhere three repeating errors:
- Uncaught TypeError: Cannot read property 'then' of undefined
    at BimServerGeometryLoader.start (BimServerGeometryLoader.js?bust=1529648699445:125)

- Uncaught TypeError: callback is not a function
    at call (bimserverclient.js?_v=1529648699449:255)

bimserverclient.js?_v=1529648699449:258 Uncaught TypeError: callback is not a function
    at BimServerClient.getSerializerByPluginClassName (bimserverclient.js?_v=1529648699449:258)

anything im issing here in what i should have done?

thanks
Or

**Comment by ericvoignier** [comment]
Hi, same problems with _bimsurfer2_ wrong path folder and then 

> Uncaught TypeError: Cannot read property 'then' of undefined
>     at BimServerGeometryLoader.start (BimServerGeometryLoader.js?bust=1531325697427:125)
>     at BimServerModelLoader.loadOids (BimServerModelLoader.js?bust=1531325697427:82)
>     at BimServerApiPromise.callback (BimServerModelLoader.js?bust=1531325697427:16)
>     at BimServerApiPromise.fire (bimserverapipromise.js:56)
>     at bimServerApi.call (model.js:744)
>     at multiCall (bimserverclient.js?_v=1531325697435:877)
>     at getJson (bimserverclient.js?_v=1531325697435:653)
>     at XMLHttpRequest.xhr.onload (bimserverclient.js?_v=1531325697435:538)

Did you found a solution ? 
thxs Eric

Same as  [BIMserver issue #775](https://github.com/opensourceBIM/BIMserver/issues/775)

**Comment by orashkenazi** [comment]
Nope. i abandoned this..
and frankly I'm quite hopeless with all the bimserver project and not  only bimsurfer..
I find it very hard to find required information and I'm finding myself reverse engineering codes to understand simple issues...

very bad documentation from a project that aims to "change to world"

**Comment by bexiaohe** [comment]
just delete ') then(', it's ok,But The problems I met were far more than that.It's terrible.

**Comment by phiqus** [comment]
any updates? I encounter the same problem. I'm assuming there is some sort of clash of ES(3-6) between libraries. the BIMserverAPI libraries are in ES3. BimSurfer libraries I believe are newer. but that won't help I suppose. It's hard to understand all this uncommented code, that's true.

**Comment by bexiaohe** [comment]
try to pull the latest code.There will be fewer mistakes. /Laugh and cry
