### ISSUE TITLE
Doubt using DefaultMaterial.js 

### ISSUE THREAD

**Issue by mohanasaraf** [opensourceBIM/BIMsurfer-before2019#252]
I am able to see/update the colours defined for IfcColumn category but the colours defined in the file for other categories doesn't have any effect on the model. I have the exact same categories in my model. 

For information - 
I have created a separate Bim Surfer (V2) project and loading my model from BIM Server.

**Comment by aothms** [comment]
Those colours are only defaults used as fallback if there is no color defined in the IFC file itself. If you want DefaultMaterials to always have control you might be able to set `colors` to `null` e.g. here [1], but I didn't test that.

[1] https://github.com/opensourceBIM/BIMsurfer/blob/master/bimsurfer/src/xeoViewer/xeoViewer.js#L352

**Comment by mohanasaraf** [comment]
Hi @aothms thanks for such a prompt response. This works. :+1:
