### ISSUE TITLE
scenejs Version upgrades to 4.2.0 

### ISSUE THREAD

**Issue by gengjl** [opensourceBIM/BIMsurfer-before2019#257]
Can you upgrade the version to scenejs V4.2.0？ 
thanks！

**Comment by rubendel** [comment]
Sorry v1 is not maintained anymore, also SceneJS isn't.

**Comment by gengjl** [comment]
thank you ,I downloaded bimsurfer-0.0.43 on bimserver V1.5.101, bimsurfer used scenejs, can I upgrade to scenejs to Version 4.2.0?
thanks！

**Comment by gengjl** [comment]
@rubendel
