### ISSUE TITLE
Error while loading bimviews via eclipse.

### ISSUE THREAD

**Issue by veerakumarasamyv** [opensourceBIM/BIMsurfer-before2019#258]
Hi all, 
Good well, I am trying to run the bimviews via the eclipse. while loading the bimviews i got error as added below screenshot. if the js files missing is the issue mean where i get the files ? i tried to find those js in git. but no result that i expect. Please help me with in this issue. thanks in advance..!

![image](https://user-images.githubusercontent.com/41254855/43354055-9832d738-9262-11e8-95e2-e6231e36413c.png)

![image](https://user-images.githubusercontent.com/41254855/43354088-0daae21c-9263-11e8-8b49-312d7ef7bfdc.png)

**Comment by rubendel** [comment]
It's missing BIMsurfer, has been answered before.

**Comment by veerakumarasamyv** [comment]
Hi Rubendel, Thanks for the reply..

This is my eclipse project setup. and i added the bimsurfer please check, guide me if i am wrong rubendel..


![image](https://user-images.githubusercontent.com/41254855/43354526-7b73c4b4-926b-11e8-9a7e-bbd6518998e9.png)

![image](https://user-images.githubusercontent.com/41254855/43354665-1c9f7840-926e-11e8-9fe8-585efb6d0e13.png)

![image](https://user-images.githubusercontent.com/41254855/43354799-2d271c16-9270-11e8-83e8-8f6674ac4d12.png)

**Comment by rubendel** [comment]
You need BIMsurfer V1 (it's a branch)

**Comment by veerakumarasamyv** [comment]
Thank you so much rubendel. It's fixed.
