### ISSUE TITLE
array in dataToInfo of BimServerGeometryLoader is undefined

### ISSUE THREAD

**Issue by xiaohujing** [opensourceBIM/BIMsurfer-before2019#273]
![image](https://user-images.githubusercontent.com/34702186/49433884-f5ec1600-f7ed-11e8-8e6c-5d785f3139f6.png)
In BimServerGeometryLoader .js, every element of dataToInfo is undefined, it caused  o.viewer.getObject( BimServerGeometryLoader -- about line 412 ) also undefined and Parsing is stopped. Not found any element.
![image](https://user-images.githubusercontent.com/34702186/49434252-bc67da80-f7ee-11e8-9ca2-02bf6ea35ab0.png)
Please help me analyze which step is wrong. Thanks。
bimserver v1.5.117(I have tried 1.5.109,also the same error)
bimsurfer is the latest。

**Comment by GMDIT** [comment]
Hello, 
I have the same problem, did you have solved it?

**Comment by kanbang** [comment]
I have the same problem, did you have solved it? 🤣

**Comment by xiaohujing** [comment]
Update the latest bimserverclient,
