### ISSUE TITLE
What is the difference between master and v1?

### ISSUE THREAD

**Issue by JanoSlivka** [opensourceBIM/BIMsurfer-before2019#274]
I use BimSurfer to show ifc model from bimserver. I'm currently using the version master, but releases are from v1. Which version should I use?

**Comment by aothms** [comment]
V1 is integrated into the BIMserver web-interface (bimvie.ws) and uses SceneJS. V2 (master) has a more modular structure and an API and uses the more recent xeogl. What to use is up to you.
