### ISSUE TITLE
Exported geometry for WallStandardCase covers windows

### ISSUE THREAD

**Issue by rehno-lindeque** [opensourceBIM/BIMsurfer-before2019#35]
The exported geometry for WallStandardCase covers the windows of the house model. (Something to do with the IFC geometry engine, or something about WallStandardCase that needs to be taken into consideration? What's the difference between Wall and WallStandardCase?)

**Comment by rehno-lindeque** [comment]
Strangely this only seems to occur if the object has the material "WallStandardCase", if it has the material "Something" or "Wall" then it displays fine.

Theory: it might somehow be due to the order of objects in the scenegraph? I.e. when you diff the two models, wallstandardcase appears earlier in the model (right after the "sunlight" node) than "something"

**Comment by rehno-lindeque** [comment]
Yes, it appears to be ordering in the scenegraph. If the material is called "WallStandardCase" but in a different position - it renders fine.

**Comment by rehno-lindeque** [comment]
Actually wrong again, now it looks like it works simply with "WallStandardCase" material assigned... will leave this issue open for a while just to make sure.

**Comment by rehno-lindeque** [comment]
The problem re-occured now... actually it looks like the serializer some times exports the geometry differently! Very strange.

**Comment by rehno-lindeque** [comment]
Something appears to be broken in BIMserver: Either the EmfSerializer or IfcEngineModel

The correct model has far more vertices than the incorrect one, perhaps it is something with the way the IfcEngine handles concave sections? Will need to ask the BIMserver devs for help on this one.

``` C++
IfcModelInterface ifcModel = new IfcModel();
convertToSubset(ifcObject.eClass(), ifcObject, ifcModel, new HashMap<EObject, EObject>());
EmfSerializer serializer = getPluginManager().requireIfcStepSerializer();
serializer.init(ifcModel, getProjectInfo(), getPluginManager());
try {
    IfcEngineModel model = ifcEngine.openModel(serializer.getBytes());
    try {
        model.setPostProcessing(true);
        IfcEngineGeometry geometry = model.finalizeModelling(model.initializeModelling());
```

**Comment by rehno-lindeque** [comment]
It is also strange that the order of things are sometimes swapped around in the serializer. There is something non-deterministic going on. 

...It could be the hashmaps:

Maybe there's something not being cleaned up properly in the IFC engine - when geometry is exported in a different order (due to the hash maps being ordered in a non-deterministic way?) it has a different effect on the modelling.

**Comment by rehno-lindeque** [comment]
Export of walls currently appears to work after adding extra IFC properties. 

However, this might crop up again - might need to revert to an older version of the serializer some time to reproduce.

**Comment by rehno-lindeque** [comment]
We'll see if this is reproduced in any other models with issue #52

**Comment by berlotti** [comment]
This is a 'bimserver' configuration issue.

**Comment by rehno-lindeque** [comment]
WON'T FIX - this is not a bug, it's just a configuration setting in BIMserver serializers...

**Comment by rehno-lindeque** [comment]
Oh, I still had my window open, you beat me to closing Léon ;)

**Comment by rehno-lindeque** [comment]
This is a BIMserver issue. It appears that some times it doesn't correctly set the configuration? Changing the GuidanceProvider and restarting BIMserver appears to help.

**Comment by berlotti** [comment]
well be fixed on bimserver side: http://code.google.com/p/bimserver/issues/detail?id=303

(was only fixed for wall, will also be fixed for wallstandardcase)
