### ISSUE TITLE
Transparency for windows

### ISSUE THREAD

**Issue by rehno-lindeque** [opensourceBIM/BIMsurfer-before2019#38]
Add transparency to the windows

**Comment by berlotti** [comment]
The transparancy/material is stored in the IFC. In the current Collada project you'll find an example how to find this attributes.

**Comment by rehno-lindeque** [comment]
Thanks, actually in the Collada project there's a fixed alpha value written for windows... (but for other materials it calls IfcSurfaceStyleRendering.getTransparency). I'm doing the same at the moment.

P.S. The two things still missing for transparency to work, a flag node for transparency and distance sorting via layers nodes...

**Comment by rehno-lindeque** [comment]
Note to self: https://github.com/xeolabs/scenejs/wiki/material and [Transparency with layers](http://scenejs.wikispaces.com/node+-+layer#x-Ordered Selection of Layers-Transparency with Layers)

**Comment by rehno-lindeque** [comment]
Transparency flag has been added to the exporter. Sorted layers still remain
