### ISSUE TITLE
Unable to authenticate to BIMServer from BIMSurfer on Mac Lion

### ISSUE THREAD

**Issue by smuctate** [opensourceBIM/BIMsurfer-before2019#66]
Running on Safari 5.1.2 (and previously 5.1.1) on Mac OS X Lion.

BIMServer running on localhost:8082 - able to authenticate separately with no problem.

BIMServer running on localhost: 8000 - using simple web server (python - as per instructions)

File->BIM Server Project

Enter credentials and submit - "Login request failed" almost instantly.

**Comment by rehno-lindeque** [comment]
Thanks, could you try running Safari with this command please? (From your console)

```
open -a '/Applications/Safari.app' --args --disable-web-security
```

Unfortunately I'm a bit busy at the moment but in the future hopefully this will be easier...

**Comment by smuctate** [comment]
Thanks for the quick response.

I'm afraid this made/makes no difference. 

Is there any way I can log what it is trying to do (and then send this (error, I assume) to you)?

**Comment by rehno-lindeque** [comment]
Thanks, yes this will help: Please open the error console, refresh the page and then repeat the steps to get the error.

I think that in Safari you choose "Show Error Console" from the Develop menu (http://developer.apple.com/library/safari/#documentation/appleapplications/Conceptual/Safari_Developer_Guide/PrototypingYourWebsite/PrototypingYourWebsite.html)
