### ISSUE TITLE
Upgrade SceneJS lib for mobile compatibility updates

### ISSUE THREAD

**Issue by xeolabs** [opensourceBIM/BIMsurfer-before2019#67]
SceneJS now has mediump  shader vars to allow compatibility with mobile devices : 

Latest build at SceneJS.org downloads

**Comment by rehno-lindeque** [comment]
Thanks Lindsay, I'll upgrade!

**Comment by xeolabs** [comment]
I'll test on my new Android phone when this is done. SceneJS examples work ok. cheers, Lk

**Comment by berlotti** [comment]
Working on a complete new BIM Surfer at this branche: https://github.com/opensourceBIM/BIMsurfer/tree/Bryan
