### ISSUE TITLE
IfcBeam not correctly serialized by BimServer? 

### ISSUE THREAD

**Issue by giohappy** [opensourceBIM/BIMsurfer-before2019#74]
Hi, 
my IFC model contains beams, modeled as IfcBeam objects. 
The moddl is shown correctly in BimSurfer except beams. 
Looking into the json it seems that beams geometries aren't there. 

Are BimServer SceneJs serializer and BimSurfer expected to manage beams? 

Thanks, 
Giovanni

**Comment by coryasilva** [comment]
Maybe no help, but beams are showing up in my model.  (It is the Revit Sample Architectural Model exported via IFC exporter).

**Comment by giohappy** [comment]
Hi,
the conversation was moved to the BIMServer support forum. It has been solved.
http://support.bimserver.org/bimserver/topics/ifcbeam_objects_dont_get_serialized_correctly_for_scenejs
