### ISSUE TITLE
Util.js

### ISSUE THREAD

**Issue by coryasilva** [opensourceBIM/BIMsurfer-before2019#76]
Consider testing for "str" in the Util.js file line 6.

```
RegExp.escape = function (str) {
    if (str) {
         return str.replace(/([;&,\.\+\*\~':"\!\^#$%@\[\]\(\)=>\|])/g, '\\$1');
    }
};
```

**Comment by berlotti** [comment]
Working on a complete new BIM Surfer at this branche: https://github.com/opensourceBIM/BIMsurfer/tree/Bryan
