### ISSUE TITLE
setAllWallsTransparent

### ISSUE THREAD

**Issue by coryasilva** [opensourceBIM/BIMsurfer-before2019#78]
Add "Ifc" to index variable to fix transparency.

Existing:
var index = sceneData.ifcTypes.indexOf('WallStandardCase');
var roofIndex = sceneData.ifcTypes.indexOf('Roof');

Should Be:
var index = sceneData.ifcTypes.indexOf('IfcWallStandardCase');
var roofIndex = sceneData.ifcTypes.indexOf('IfcRoof');

**Comment by berlotti** [comment]
Working on a complete new BIM Surfer at this branche: https://github.com/opensourceBIM/BIMsurfer/tree/Bryan
