### ISSUE TITLE
Doesn't show IFC model from BIM Server

### ISSUE THREAD

**Issue by stanislavalbreht** [opensourceBIM/BIMsurfer-before2019#82]
We're trying to use BIM Surfer for viewing our IFC model.

We've installed BIM Server 1.2, imported our model there. It's currently available here: https://dl.dropboxusercontent.com/u/51934622/bim_server_creds.txt

We're trying to open it using latest BIM Serfer, we see running progress, loading floors, walls, doors, when it's finished (sometimes it's not) we see these elements in the tree on the left but we see only black screen instead of 3D model at the center. There are 12 JS errors about not defined object and some about "org.bimserver.servlets.JsonApiServlet - Invalid JSON request" on the server. Tried in Firefox and Chrome.

Server log is available at https://dl.dropboxusercontent.com/u/51934622/bim_server.log.

Will appreciate any advice on what can be wrong.

**Comment by rubendel** [comment]
The "Invalid JSON request" messages can be ignored, those won't be shown anymore in 1.2.1 (not released yet).

The interesting messages are the 12 JS errors, can you post those as well?

**Comment by stanislavalbreht** [comment]
Double checked it: JS errors appear when you move mouse over the black area. There are no any when just opened the project.

![bimbug](https://f.cloud.github.com/assets/1651266/1216126/35f79fe2-2681-11e3-97ef-2940a0a094c8.png)

**Comment by dlabz** [comment]
I had this happen when server crashes on checkin, due outOfMemory error. If generating geometry fails, server returns empty geometries, resulting in this error. Check in the "Network" tab of the debugger... if /download links show empty JSON arrays, that's your problem.

**Comment by stanislavalbreht** [comment]
Look like some responses have empty JSONs but some do have geometric data. It'd be strange if it was memory of the server problem because we've tried to enter 4Gb as a heap size before starting it and model is't very large (~15Mb) - maybe it is't enough though? There are no OutOfMemory exceptions in the server log.

**Comment by dlabz** [comment]
Might be a bad ifc file. 
Still, it's empty json arrays that cause the issue, at least from my experience. 
4GB should be enough.

**Comment by stanislavalbreht** [comment]
Yes, perhaps it's file issue because the new file is loaded normally. Still it's interesting that this model opens well in the app where it's created.
