### ISSUE TITLE
Doesn't show IFC model from BIM Server

### ISSUE THREAD

**Issue by silent-cz** [opensourceBIM/BIMsurfer-before2019#83]
Hello all,
I trying to use BIM Surfer-master for viewing a test IFC model.
I have installed BIM server latest version 1.2 under the apache-tomcat-7.0.40 server.
I have successfully logged in the BIM server and opened a chosen project as well.

We're trying to open it using latest BIM Serfer-master, we see running progress, loading floors, walls, doors, when it's finished (sometimes it's not) we see these elements in the tree on the left but we see only black screen instead of 3D model at the center. 

There did not occure errors, please see the attach image.

Nevertheless the 3D model is not appearing.

Please advise how to proceed.
![bimsurfermaster](https://f.cloud.github.com/assets/5948063/1550168/ae3b8296-4dfc-11e3-9d70-eaed6f4e673a.png)

**Comment by rubendel** [comment]
Does the BIMserver log have any errors?

**Comment by silent-cz** [comment]
Hi Ruben, thank you for your reply.
I did not find any errors. Please, see the mapped link of BIM server log:

http://81.19.3.141/dwld/bimserver.log

Radek

**Comment by silent-cz** [comment]
Hi Ruben, please try web acces to my BIM server:

http://81.19.3.141:1024/BIMsurfer-master/

BIMserver: http://10.0.0.250:1024
login: admin@interplan.cz
pwd: admin

Radek

Comment: this webaccess is enabled for a range of IP addresses 70.192.0.0 - 70.223.255.255.

**Comment by rubendel** [comment]
According to the logfile, there is a problem with the IFCEngine.

17:40:36 ERROR java.lang.UnsatisfiedLinkError: Unable to load library 'ifcengine': /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/apache-tomcat-7.0.40/webapps/ROOT/WEB-INF/tmp/TNOEngineSeries/libifcengine.so)
    at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:164)
    at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:237)
    at com.sun.jna.Library$Handler.<init>(Library.java:140)
    at com.sun.jna.Native.loadLibrary(Native.java:375)

If possible, you should upgrade to version GLIBC_2.14 of libc or ask the IFCEngine developer to build against other GLIBC versions.

**Comment by silent-cz** [comment]
Hi Ruben, thank you for your reply and advice, but it still does not work.

I have made ​​a new linux server Ubuntu, distribution ubuntu-12.04.3-server-amd64.

I found out the GNU libc version: 2.15 using the glibc-version command
(perhaps not much difference between 2.14 and 2.15 of versions).

There did not occure errors in the bimserver.log, no errors "Unable to load library 'ifcengine': /lib64/libc.so.6: version `GLIBC_2.14' not found".

## Please advise where the issues can be?

Actual bimserver.log:
http://81.19.3.141/dwld/bimserver.log

Information about the components and systems:

My Linux Distribution Name and Version:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.3 LTS"
NAME="Ubuntu"
VERSION="12.04.3 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.3 LTS)"
VERSION_ID="12.04"

Linux BIM 3.8.0-29-generic #42~precise1-Ubuntu SMP Wed Aug 14 16:19:23 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

HW:
6GB RAM, CPU 4 core

JVM:
java version "1.6.0_27"
OpenJDK Runtime Environment (IcedTea6 1.12.6) (6b27-1.12.6-1ubuntu0.12.04.2)
OpenJDK 64-Bit Server VM (build 20.0-b12, mixed mode)

TOMCAT:
Using CATALINA_BASE:   /opt/apache-tomcat-7.0.40
Using CATALINA_HOME:   /opt/apache-tomcat-7.0.40
Using CATALINA_TMPDIR: /opt/apache-tomcat-7.0.40/temp
Using JRE_HOME:        /usr
Using CLASSPATH:       /opt/apache-tomcat-7.0.40/bin/bootstrap.jar:/opt/apache-tomcat-7.0.40/bin/tomcat-juli.jar
Server version: Apache Tomcat/7.0.40
Server built:   May 5 2013 08:54:06
Server number:  7.0.40.0
OS Name:        Linux
OS Version:     3.8.0-29-generic
Architecture:   amd64
JVM Version:    1.6.0_27-b27
JVM Vendor:     Sun Microsystems Inc.

**Comment by silent-cz** [comment]
Hi Ruben, I am sorry, it is working.

I did folloeing steps:

STOP TOMCAT:
cd /opt/apache-tomcat-7.0.40/bin
./shutdown.sh

DELETE OLD ROOT directory:
cd /opt/apache-tomcat-7.0.40/webapps
rm -rf ROOT
(comment: the ROOT.war is renamed bimserver-1.2.war from http://bimserver.org/download/ )

START TOMCAT:
cd /opt/apache-tomcat-7.0.40/bin
./startup.sh

After start up the TOMCAT server, it was rebuilt ROOT.war and then it was re-setup BIM in the web page http://10.0.0.210:1024/admin

Radek

**Comment by rubendel** [comment]
Great!
