### ISSUE TITLE
Wordpress

### ISSUE THREAD

**Issue by ibuilder** [opensourceBIM/BIMsurfer-before2019#85]
With the introduction of Autodesk's Bim 360 Glue, any though of integrating BimSurfer as a wordpress plugin like:

http://wordpress.org/plugins/autodesk-freewheel-viewer/

or 

http://codecanyon.net/item/wordpress-stl-3d-viewer-shortcode/3258893

Would be huge for model delivery on a project.  Just a thought.

**Comment by berlotti** [comment]
We had simular thoughts but are bound by funding. Would you like to work on this, or even sponsor it?
