### ISSUE TITLE
new examples from branch Bryan don't work

### ISSUE THREAD

**Issue by Odi55555** [opensourceBIM/BIMsurfer-before2019#89]
Hi,

I'm not sure if the new examples are finished, but anyway I can't show any ifc files.

First I tried BIMsurfer with a BIMserver 1.3.0-RC5-2014-02-11, but then I wrote that BIMsurfer doesn't work with the 1.3 API. Now I've a BIMserver 1.2.-20130706 up and running. If I roll back to the master branch, where the demo was loaded through the index.html, everything works fine. 

But the example1 doesn't display anything. I'm able to login and choose one of my projects. Then I fixed an error in Viewer.js at getSerializerByPluginClassName (https://github.com/Odi55555/BIMsurfer/commit/6162f76dd7f0d9d4d413aef393d44912508463be) 
But now I get two errors that setBinaryDataListener and downloadViaWebsocket are not defined. Are you using another API?

**Comment by dlabz** [comment]
The BIMsurfer master is only compatible with the BIMServer master branch, due recent changes.

Cheers

**Comment by berlotti** [comment]
BIM Surfer is under heavy redevelopment. BIMserver is also still not final. We are working hard to get both stable as soon as possible.

**Comment by Odi55555** [comment]
Thx for the fast feedback and great to hear that you're working on BIMsurfer.
Looking forward to test the new releases.
