### ISSUE TITLE
Not showing any thing

### ISSUE THREAD

**Issue by navneetccna** [opensourceBIM/BIMsurfer-before2019#95]
Hi i installed latest version of bimserver and bimsurfer in  bimsurfer viewer nothing is coming after clicking on project. please provide me bimserver version in which bimsurfer working fine.
Only showing 0% (Loading Geometry)

Server data

03-04-2014 19:45:09 DEBUG org.bimserver.shared.interfaces.bimsie1.Bimsie1NotificationRegistryInterface - NOT Sending update directly for topic 10
03-04-2014 19:45:09 INFO  org.bimserver.cache.DiskCacheManager - Start caching 393219-[IfcWindow].dat
03-04-2014 19:45:09 DEBUG org.bimserver.notifications.ProgressTopic - Sending STATE 0
03-04-2014 19:45:09 DEBUG org.bimserver.servlets.JsonWebsocketReflector - WS: {"request":{"interface":"Bimsie1NotificationInterface","method":"progress","parameters":{"topicId":10,"state":{"__type":"SLongActionState","end":null,"errors":[],"infos":[],"oid":-1,"progress":0,"rid":0,"stage":1,"start":1396534509699,"state":"STARTED","title":"Starting download","warnings":[]}}}}
03-04-2014 19:45:09 DEBUG org.bimserver.notifications.ProgressTopic - Sending STATE 100
03-04-2014 19:45:09 DEBUG org.bimserver.servlets.JsonWebsocketReflector - WS: {"request":{"interface":"Bimsie1NotificationInterface","method":"progress","parameters":{"topicId":10,"state":{"__type":"SLongActionState","end":1396534509717,"errors":[],"infos":[],"oid":-1,"progress":100,"rid":0,"stage":2,"start":1396534509699,"state":"FINISHED","title":"Done","warnings":[]}}}}
03-04-2014 19:45:09 INFO  org.bimserver.cache.DiskCacheManager - Done caching 720899-[IfcWall].dat
03-04-2014 19:45:09 INFO  org.bimserver.cache.DiskCacheManager - Done caching 851971-[IfcWindow].dat
0 ms
03-04-2014 19:45:09 INFO  org.bimserver.cache.DiskCacheManager - Done caching 393219-[IfcWindow].dat
03-04-2014 19:45:55 INFO  org.bimserver.longaction.LongActionManager - Cleaning up long running action: Download

**Comment by navneetccna** [comment]
I am using BIMServer 1.3
PFA
![1](https://cloud.githubusercontent.com/assets/210475/2612660/bcb763c4-bbc7-11e3-8435-2831088f90d7.png)
![2](https://cloud.githubusercontent.com/assets/210475/2612661/bdcfa53c-bbc7-11e3-9ff2-f7c87f968763.png)
![3](https://cloud.githubusercontent.com/assets/210475/2612659/bcabf52a-bbc7-11e3-85c4-7c402f5ec183.png)
![4](https://cloud.githubusercontent.com/assets/210475/2612658/bcabcdb6-bbc7-11e3-8b9a-2c10053c8261.png)

**Comment by rubendel** [comment]
Does it work if you disable disk caching on the server?
