### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by navneetccna** [opensourceBIM/BIMsurfer-before2019#98]
07-04-2014 11:24:30 INFO  org.ifcopenshell.IfcOpenShellEngine - Initializing IfcOpenShell engine
# 
# A fatal error has been detected by the Java Runtime Environment:
# 
# SIGSEGV (0xb) at pc=0x1afe996e, pid=4506, tid=520039232
# 
# JRE version: OpenJDK Runtime Environment (7.0_51) (build 1.7.0_51-b00)
# Java VM: OpenJDK Server VM (24.45-b08 mixed mode linux-x86 )
# Problematic frame:
# C  [libIfcJni.so+0xb696e]  std::map<std::string, IfcGeom::SurfaceStyle, std::less<std::string>, std::allocator<std::pair<std::string const, IfcGeom::SurfaceStyle> > >::~map()+0x166fe
# 
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
# 
# An error report file with more information is saved as:
# /root/bimn/bimserver/hs_err_pid4506.log
# 
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
# http://icedtea.classpath.org/bugzilla
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by coryasilva** [comment]
@navneetccna Can you correct the markdown conflict

**Comment by rubendel** [comment]
This has nothing to do with BIMsurfer, it's IfcOpenShell that's crashing, please open an issue in the appropriate place.
